/**
 * CIUDADES REALES POR PAÍS Y ZONA: de dónde sale y adónde llega una etapa que no trae ciudades.
 *
 * El dueño: «cada vez que mencione una etapa, que diga siempre el origen y destino». Las 60 ediciones
 * reales (`editions.ts`) y las 250 carreras de equipos restantes (`raceRoutes.ts`) ya tienen salida y
 * llegada de autoría; los 532 campeonatos nacionales no tenían ninguna. Esta tabla es el CONTENIDO del
 * que las saca el calendario: para cada país de `COUNTRIES`, una lista de ciudades reales de la zona
 * geográfica (`GeoZone`) en que la gramática dibuja sus etapas.
 *
 * Reglas de lectura, que son también las del fichero:
 *  - la clave de zona es la de `zonaDe(country)`, la que da la firma geográfica a sus nacionales
 *    (§6.6). En un país con varias zonas (FR, BE, IT, ES y los tres alpinos) la lista es SOLO de esa
 *    zona: el campeonato de Francia se corre donde la gramática dibuja su relieve (`bretana`, con el
 *    Loira y Normandía por proxy, como en `regions.ts`), no en Niza;
 *  - un país de `TERRITORIOS` lleva de 10 a 30 ciudades, más cuanto más pesa en el calendario, para
 *    que la ciudad del campeonato rote entre temporadas; un país que cae a `FALLBACK` (solo corre su
 *    campeonato) lleva unas pocas;
 *  - nombres en ASCII, en su grafía local sin diacríticos o en la inglesa habitual, como el resto del
 *    calendario (`Antwerpen`, `Milano`, `Lisboa`, `Koln`, `Copenhagen`, `Prague`);
 *  - es DATO: se corrige aquí, nunca en el código que la lee. Ninguna ciudad entra en una tirada del
 *    perfil (el sorteo de la ciudad tiene su propio subflujo, `ciudad`, en `edition.ts`).
 *
 * `ciudades.test.ts` comprueba que todo país tiene su lista en su zona, que son ASCII, sin repetidos y
 * del tamaño que dice su peso.
 */
import type { GeoZone } from './geo.js'

export const CIUDADES: Readonly<Record<string, Partial<Record<GeoZone, readonly string[]>>>> = {
  // --- Países con territorio (geo.ts, TERRITORIOS) -------------------------------------------------
  // Francia: la zona de sus nacionales es `bretana` (Bretaña, con el Loira y Normandía por proxy).
  FR: {
    bretana: [
      'Rennes',
      'Brest',
      'Quimper',
      'Lorient',
      'Vannes',
      'Saint-Brieuc',
      'Saint-Malo',
      'Plouay',
      'Saint-Nazaire',
      'Nantes',
      'Angers',
      'Laval',
      'Le Mans',
      'Cholet',
      'La Roche-sur-Yon',
      'Les Herbiers',
      'Caen',
      'Cherbourg',
      'Saint-Lo',
      'Alencon',
      'Avranches',
      'Granville',
      'Lannion',
      'Morlaix',
      'Pontivy',
      'Dinan',
      'Fougeres',
      'Vitre',
      'Chateaulin',
      'Loudeac',
    ],
  },
  // Bélgica: `flandes` (sus nacionales no suben a las Ardenas).
  BE: {
    flandes: [
      'Brugge',
      'Gent',
      'Antwerpen',
      'Kortrijk',
      'Roeselare',
      'Oudenaarde',
      'Waregem',
      'Ieper',
      'Aalst',
      'Mechelen',
      'Leuven',
      'Hasselt',
      'Genk',
      'Sint-Niklaas',
      'Oostende',
      'Knokke-Heist',
      'De Panne',
      'Harelbeke',
      'Wevelgem',
      'Tielt',
      'Geraardsbergen',
      'Ninove',
      'Herentals',
      'Turnhout',
      'Lommel',
    ],
  },
  NL: {
    flandes: [
      'Amsterdam',
      'Rotterdam',
      'Den Haag',
      'Utrecht',
      'Eindhoven',
      'Tilburg',
      'Breda',
      'Nijmegen',
      'Arnhem',
      'Maastricht',
      'Valkenburg',
      'Sittard',
      'Roermond',
      'Venlo',
      'Zwolle',
      'Groningen',
      'Leeuwarden',
      'Assen',
      'Emmen',
      'Apeldoorn',
      'Enschede',
      'Almere',
      'Hoogerheide',
      'Middelburg',
    ],
  },
  LU: {
    ardenas: [
      'Luxembourg',
      'Esch-sur-Alzette',
      'Differdange',
      'Dudelange',
      'Ettelbruck',
      'Diekirch',
      'Wiltz',
      'Clervaux',
      'Mondorf-les-Bains',
      'Remich',
      'Echternach',
      'Mersch',
    ],
  },
  // Italia: `italia_norte` (la llanura del Po, los lagos y la Liguria).
  IT: {
    italia_norte: [
      'Milano',
      'Torino',
      'Genova',
      'Bergamo',
      'Brescia',
      'Como',
      'Varese',
      'Verona',
      'Vicenza',
      'Padova',
      'Treviso',
      'Venezia',
      'Udine',
      'Trieste',
      'Pordenone',
      'Novara',
      'Alessandria',
      'Asti',
      'Cuneo',
      'Biella',
      'Pavia',
      'Cremona',
      'Mantova',
      'Piacenza',
      'Lecco',
      'Legnano',
      'Sanremo',
      'Savona',
    ],
  },
  // España: `cantabrico` (País Vasco, Cantabria y Asturias, con Navarra y Galicia por proxy).
  ES: {
    cantabrico: [
      'Bilbao',
      'San Sebastian',
      'Vitoria',
      'Eibar',
      'Durango',
      'Irun',
      'Getxo',
      'Santander',
      'Torrelavega',
      'Laredo',
      'Oviedo',
      'Gijon',
      'Aviles',
      'Llanes',
      'Cangas de Onis',
      'Pamplona',
      'Estella',
      'Tudela',
      'A Coruna',
      'Santiago de Compostela',
      'Lugo',
      'Ourense',
      'Pontevedra',
      'Vigo',
      'Ferrol',
    ],
  },
  AD: {
    pirineos: [
      'Andorra la Vella',
      'Escaldes-Engordany',
      'Encamp',
      'Canillo',
      'La Massana',
      'Ordino',
      'Sant Julia de Loria',
      'Pas de la Casa',
      'Soldeu',
      'Arinsal',
    ],
  },
  PT: {
    portugal: [
      'Lisboa',
      'Porto',
      'Braga',
      'Guimaraes',
      'Viseu',
      'Coimbra',
      'Leiria',
      'Aveiro',
      'Viana do Castelo',
      'Vila Real',
      'Braganca',
      'Guarda',
      'Covilha',
      'Castelo Branco',
      'Santarem',
      'Evora',
      'Beja',
      'Faro',
      'Tavira',
      'Setubal',
      'Torres Vedras',
      'Mafra',
      'Fafe',
      'Felgueiras',
    ],
  },
  DE: {
    centroeuropa: [
      'Berlin',
      'Hamburg',
      'Munchen',
      'Koln',
      'Frankfurt',
      'Stuttgart',
      'Dusseldorf',
      'Dortmund',
      'Essen',
      'Bremen',
      'Hannover',
      'Leipzig',
      'Dresden',
      'Nurnberg',
      'Freiburg',
      'Karlsruhe',
      'Bielefeld',
      'Chemnitz',
      'Erfurt',
      'Regensburg',
    ],
  },
  HU: {
    centroeuropa: [
      'Budapest',
      'Debrecen',
      'Szeged',
      'Miskolc',
      'Pecs',
      'Gyor',
      'Nyiregyhaza',
      'Kecskemet',
      'Szekesfehervar',
      'Eger',
      'Veszprem',
      'Sopron',
    ],
  },
  CZ: {
    centroeuropa: [
      'Prague',
      'Brno',
      'Ostrava',
      'Plzen',
      'Olomouc',
      'Liberec',
      'Hradec Kralove',
      'Pardubice',
      'Ceske Budejovice',
      'Zlin',
      'Jihlava',
      'Karlovy Vary',
    ],
  },
  SK: {
    centroeuropa: [
      'Bratislava',
      'Kosice',
      'Presov',
      'Zilina',
      'Banska Bystrica',
      'Nitra',
      'Trnava',
      'Trencin',
      'Martin',
      'Poprad',
      'Piestany',
    ],
  },
  PL: {
    centroeuropa: [
      'Warszawa',
      'Krakow',
      'Gdansk',
      'Wroclaw',
      'Poznan',
      'Lodz',
      'Katowice',
      'Lublin',
      'Bialystok',
      'Rzeszow',
      'Szczecin',
      'Torun',
      'Bydgoszcz',
      'Kielce',
      'Opole',
      'Zakopane',
    ],
  },
  // Los tres alpinos: `alpes` (la zona de mayor peso; empata con `centroeuropa` y gana la primera).
  AT: {
    alpes: [
      'Innsbruck',
      'Salzburg',
      'Kitzbuhel',
      'Zell am See',
      'Lienz',
      'Bregenz',
      'Feldkirch',
      'Bad Gastein',
      'Kufstein',
      'Villach',
      'Klagenfurt',
      'Schladming',
      'Bischofshofen',
      'Sankt Johann im Pongau',
      'Landeck',
    ],
  },
  SI: {
    alpes: [
      'Kranj',
      'Bled',
      'Jesenice',
      'Bovec',
      'Tolmin',
      'Kamnik',
      'Skofja Loka',
      'Radovljica',
      'Kranjska Gora',
      'Ljubljana',
      'Idrija',
      'Velenje',
    ],
  },
  CH: {
    alpes: [
      'Lugano',
      'Bellinzona',
      'Locarno',
      'Sion',
      'Martigny',
      'Brig',
      'Chur',
      'Davos',
      'St. Moritz',
      'Andermatt',
      'Interlaken',
      'Thun',
      'Luzern',
      'Grindelwald',
      'Crans-Montana',
      'Leukerbad',
      'Aigle',
      'Montreux',
    ],
  },
  DK: {
    escandinavia: [
      'Copenhagen',
      'Aarhus',
      'Odense',
      'Aalborg',
      'Esbjerg',
      'Randers',
      'Kolding',
      'Horsens',
      'Vejle',
      'Roskilde',
      'Herning',
      'Silkeborg',
      'Fredericia',
      'Viborg',
      'Holstebro',
      'Skive',
      'Svendborg',
      'Naestved',
    ],
  },
  EE: {
    escandinavia: [
      'Tallinn',
      'Tartu',
      'Parnu',
      'Narva',
      'Viljandi',
      'Rakvere',
      'Haapsalu',
      'Kuressaare',
      'Voru',
      'Paide',
    ],
  },
  LT: {
    escandinavia: [
      'Vilnius',
      'Kaunas',
      'Klaipeda',
      'Siauliai',
      'Panevezys',
      'Alytus',
      'Marijampole',
      'Palanga',
      'Druskininkai',
      'Utena',
    ],
  },
  SE: {
    escandinavia: [
      'Stockholm',
      'Goteborg',
      'Malmo',
      'Uppsala',
      'Vasteras',
      'Orebro',
      'Linkoping',
      'Helsingborg',
      'Jonkoping',
      'Norrkoping',
      'Lund',
      'Karlstad',
    ],
  },
  FI: {
    escandinavia: [
      'Helsinki',
      'Espoo',
      'Tampere',
      'Turku',
      'Oulu',
      'Jyvaskyla',
      'Lahti',
      'Kuopio',
      'Pori',
      'Joensuu',
    ],
  },
  LV: {
    escandinavia: [
      'Riga',
      'Daugavpils',
      'Liepaja',
      'Jelgava',
      'Jurmala',
      'Ventspils',
      'Rezekne',
      'Valmiera',
      'Sigulda',
      'Cesis',
    ],
  },
  NO: {
    escandinavia: [
      'Oslo',
      'Bergen',
      'Trondheim',
      'Stavanger',
      'Kristiansand',
      'Drammen',
      'Fredrikstad',
      'Tromso',
      'Lillehammer',
      'Hamar',
      'Alesund',
      'Bodo',
      'Larvik',
      'Skien',
      'Arendal',
    ],
  },
  GB: {
    britanicas: [
      'London',
      'Manchester',
      'Birmingham',
      'Leeds',
      'Glasgow',
      'Edinburgh',
      'Cardiff',
      'Newcastle',
      'Sheffield',
      'Bristol',
      'Liverpool',
      'Nottingham',
      'Harrogate',
      'York',
      'Kendal',
      'Stoke-on-Trent',
      'Lincoln',
      'Norwich',
      'Aberdeen',
      'Swansea',
    ],
  },
  IE: {
    britanicas: [
      'Dublin',
      'Cork',
      'Galway',
      'Limerick',
      'Waterford',
      'Kilkenny',
      'Wexford',
      'Sligo',
      'Athlone',
      'Drogheda',
      'Dundalk',
      'Killarney',
    ],
  },
  HR: {
    balcanes: [
      'Zagreb',
      'Split',
      'Rijeka',
      'Osijek',
      'Zadar',
      'Pula',
      'Sibenik',
      'Dubrovnik',
      'Karlovac',
      'Varazdin',
      'Makarska',
      'Sisak',
    ],
  },
  BA: {
    balcanes: [
      'Sarajevo',
      'Banja Luka',
      'Mostar',
      'Tuzla',
      'Zenica',
      'Bihac',
      'Trebinje',
      'Doboj',
      'Travnik',
      'Jajce',
    ],
  },
  RS: {
    balcanes: [
      'Belgrade',
      'Novi Sad',
      'Nis',
      'Kragujevac',
      'Subotica',
      'Zrenjanin',
      'Pancevo',
      'Cacak',
      'Kraljevo',
      'Smederevo',
      'Valjevo',
      'Uzice',
    ],
  },
  RO: {
    balcanes: [
      'Bucharest',
      'Cluj-Napoca',
      'Timisoara',
      'Iasi',
      'Constanta',
      'Brasov',
      'Sibiu',
      'Craiova',
      'Oradea',
      'Arad',
      'Pitesti',
      'Targu Mures',
    ],
  },
  BG: {
    balcanes: [
      'Sofia',
      'Plovdiv',
      'Varna',
      'Burgas',
      'Ruse',
      'Stara Zagora',
      'Pleven',
      'Veliko Tarnovo',
      'Sliven',
      'Kazanlak',
      'Blagoevgrad',
      'Shumen',
    ],
  },
  AL: {
    balcanes: [
      'Tirana',
      'Durres',
      'Vlore',
      'Shkoder',
      'Elbasan',
      'Korce',
      'Fier',
      'Berat',
      'Lushnje',
      'Kavaje',
    ],
  },
  XK: {
    balcanes: [
      'Pristina',
      'Prizren',
      'Peja',
      'Gjakova',
      'Mitrovica',
      'Ferizaj',
      'Gjilan',
      'Vushtrri',
      'Podujevo',
      'Suhareka',
    ],
  },
  GR: {
    balcanes: [
      'Athens',
      'Thessaloniki',
      'Patras',
      'Heraklion',
      'Larissa',
      'Volos',
      'Ioannina',
      'Kalamata',
      'Chania',
      'Rhodes',
      'Kavala',
      'Tripoli',
    ],
  },
  TR: {
    anatolia: [
      'Istanbul',
      'Ankara',
      'Izmir',
      'Antalya',
      'Bursa',
      'Konya',
      'Alanya',
      'Kayseri',
      'Eskisehir',
      'Trabzon',
      'Gaziantep',
      'Mersin',
      'Denizli',
      'Marmaris',
      'Fethiye',
      'Bodrum',
    ],
  },
  CY: {
    anatolia: [
      'Nicosia',
      'Limassol',
      'Larnaca',
      'Paphos',
      'Famagusta',
      'Kyrenia',
      'Paralimni',
      'Ayia Napa',
      'Polis',
      'Platres',
    ],
  },
  AZ: {
    anatolia: [
      'Baku',
      'Ganja',
      'Sumqayit',
      'Mingachevir',
      'Sheki',
      'Lankaran',
      'Shamakhi',
      'Quba',
      'Gabala',
      'Shirvan',
    ],
  },
  CO: {
    andes: [
      'Bogota',
      'Medellin',
      'Cali',
      'Tunja',
      'Manizales',
      'Pereira',
      'Armenia',
      'Bucaramanga',
      'Duitama',
      'Sogamoso',
      'Ibague',
      'Pasto',
      'Popayan',
      'Zipaquira',
      'Rionegro',
      'La Ceja',
    ],
  },
  EC: {
    andes: [
      'Quito',
      'Guayaquil',
      'Cuenca',
      'Ambato',
      'Riobamba',
      'Loja',
      'Ibarra',
      'Latacunga',
      'Tulcan',
      'Guano',
    ],
  },
  VE: {
    andes: [
      'Caracas',
      'Merida',
      'San Cristobal',
      'Barquisimeto',
      'Valencia',
      'Maracay',
      'Trujillo',
      'Valera',
      'Barinas',
      'Maracaibo',
      'Tovar',
      'Timotes',
    ],
  },
  GT: {
    andes: [
      'Guatemala City',
      'Quetzaltenango',
      'Antigua Guatemala',
      'Escuintla',
      'Huehuetenango',
      'Chimaltenango',
      'Coban',
      'Solola',
      'Mazatenango',
      'Totonicapan',
    ],
  },
  AR: {
    cono_sur: [
      'Buenos Aires',
      'Cordoba',
      'Rosario',
      'Mendoza',
      'San Juan',
      'San Luis',
      'Tucuman',
      'Salta',
      'Neuquen',
      'Bariloche',
      'Mar del Plata',
      'La Plata',
      'Santa Fe',
      'Parana',
      'Villa Carlos Paz',
    ],
  },
  CL: {
    cono_sur: [
      'Santiago',
      'Valparaiso',
      'Vina del Mar',
      'Concepcion',
      'La Serena',
      'Rancagua',
      'Talca',
      'Temuco',
      'Puerto Montt',
      'Chillan',
      'Antofagasta',
      'Los Andes',
    ],
  },
  US: {
    norteamerica: [
      'Los Angeles',
      'San Francisco',
      'Sacramento',
      'San Diego',
      'Santa Rosa',
      'Boulder',
      'Denver',
      'Colorado Springs',
      'Salt Lake City',
      'Asheville',
      'Philadelphia',
      'Richmond',
      'Pittsburgh',
      'Atlanta',
      'Chicago',
      'Portland',
      'Seattle',
      'Austin',
      'Tulsa',
      'Greenville',
    ],
  },
  CA: {
    norteamerica: [
      'Montreal',
      'Quebec City',
      'Toronto',
      'Ottawa',
      'Vancouver',
      'Victoria',
      'Calgary',
      'Edmonton',
      'Winnipeg',
      'Halifax',
      'Sherbrooke',
      'Gatineau',
    ],
  },
  AU: {
    australia: [
      'Adelaide',
      'Melbourne',
      'Sydney',
      'Brisbane',
      'Perth',
      'Hobart',
      'Canberra',
      'Geelong',
      'Ballarat',
      'Bendigo',
      'Wollongong',
      'Newcastle',
      'Launceston',
      'Townsville',
      'Cairns',
      'Toowoomba',
      'Mildura',
      'Albury',
    ],
  },
  NZ: {
    australia: [
      'Auckland',
      'Wellington',
      'Christchurch',
      'Hamilton',
      'Tauranga',
      'Dunedin',
      'Napier',
      'Nelson',
      'Palmerston North',
      'Rotorua',
      'Queenstown',
      'Invercargill',
    ],
  },
  JP: {
    asia_oriental: [
      'Tokyo',
      'Osaka',
      'Kyoto',
      'Nagoya',
      'Yokohama',
      'Utsunomiya',
      'Shizuoka',
      'Hiroshima',
      'Fukuoka',
      'Sapporo',
      'Sendai',
      'Kobe',
      'Nara',
      'Matsumoto',
      'Takayama',
    ],
  },
  TW: {
    asia_oriental: [
      'Taipei',
      'Taichung',
      'Tainan',
      'Kaohsiung',
      'Hualien',
      'Taitung',
      'Hsinchu',
      'Keelung',
      'Yilan',
      'Chiayi',
    ],
  },
  CN: {
    asia_oriental: [
      'Beijing',
      'Shanghai',
      'Hangzhou',
      'Nanjing',
      'Suzhou',
      'Qingdao',
      'Chengdu',
      'Kunming',
      'Guilin',
      'Xining',
      'Lanzhou',
      'Wuxi',
      'Xiamen',
      'Guangzhou',
    ],
  },
  KR: {
    asia_oriental: [
      'Seoul',
      'Busan',
      'Incheon',
      'Daegu',
      'Daejeon',
      'Gwangju',
      'Ulsan',
      'Gangneung',
      'Jeonju',
      'Chuncheon',
      'Gunsan',
      'Pyeongchang',
    ],
  },
  TH: {
    asia_oriental: [
      'Bangkok',
      'Chiang Mai',
      'Chiang Rai',
      'Phuket',
      'Pattaya',
      'Hua Hin',
      'Khon Kaen',
      'Nakhon Ratchasima',
      'Udon Thani',
      'Phitsanulok',
    ],
  },
  IN: {
    asia_oriental: [
      'New Delhi',
      'Mumbai',
      'Pune',
      'Bengaluru',
      'Chennai',
      'Hyderabad',
      'Kolkata',
      'Jaipur',
      'Ahmedabad',
      'Chandigarh',
      'Lonavala',
      'Mysuru',
    ],
  },
  MY: {
    montana_sur: [
      'Kuala Lumpur',
      'Ipoh',
      'Kuantan',
      'Kota Bharu',
      'Kuala Terengganu',
      'Alor Setar',
      'George Town',
      'Melaka',
      'Johor Bahru',
      'Seremban',
      'Genting Highlands',
      'Tanah Rata',
    ],
  },
  RW: {
    montana_sur: [
      'Kigali',
      'Huye',
      'Musanze',
      'Rubavu',
      'Rusizi',
      'Muhanga',
      'Rwamagana',
      'Nyagatare',
      'Karongi',
      'Nyanza',
    ],
  },
  MA: {
    montana_sur: [
      'Rabat',
      'Casablanca',
      'Marrakech',
      'Fes',
      'Tangier',
      'Agadir',
      'Meknes',
      'Oujda',
      'Ifrane',
      'Tetouan',
      'Ouarzazate',
      'Essaouira',
    ],
  },
  AE: {
    golfo: [
      'Dubai',
      'Abu Dhabi',
      'Sharjah',
      'Al Ain',
      'Ajman',
      'Ras Al Khaimah',
      'Fujairah',
      'Umm Al Quwain',
      'Khor Fakkan',
      'Dibba',
    ],
  },
  SA: {
    golfo: [
      'Riyadh',
      'Jeddah',
      'Dammam',
      'Khobar',
      'AlUla',
      'Taif',
      'Abha',
      'Tabuk',
      'Hail',
      'Yanbu',
    ],
  },
  OM: {
    golfo: [
      'Muscat',
      'Salalah',
      'Sohar',
      'Nizwa',
      'Sur',
      'Ibri',
      'Barka',
      'Rustaq',
      'Bahla',
      'Samail',
    ],
  },
  QA: {
    golfo: [
      'Doha',
      'Al Wakrah',
      'Al Khor',
      'Lusail',
      'Dukhan',
      'Mesaieed',
      'Al Rayyan',
      'Umm Salal',
      'Al Shamal',
      'Al Ruwais',
    ],
  },
  BJ: {
    africa_llana: [
      'Cotonou',
      'Porto-Novo',
      'Parakou',
      'Abomey',
      'Bohicon',
      'Djougou',
      'Natitingou',
      'Ouidah',
      'Lokossa',
      'Dassa-Zoume',
    ],
  },
  BF: {
    africa_llana: [
      'Ouagadougou',
      'Bobo-Dioulasso',
      'Koudougou',
      'Banfora',
      'Ouahigouya',
      'Kaya',
      'Tenkodogo',
      'Fada Ngourma',
      'Dedougou',
      'Dori',
    ],
  },
  CM: {
    africa_llana: [
      'Yaounde',
      'Douala',
      'Bamenda',
      'Bafoussam',
      'Garoua',
      'Maroua',
      'Ngaoundere',
      'Kribi',
      'Limbe',
      'Buea',
    ],
  },
  MU: {
    africa_llana: [
      'Port Louis',
      'Curepipe',
      'Quatre Bornes',
      'Vacoas',
      'Rose Hill',
      'Mahebourg',
      'Flacq',
      'Grand Baie',
      'Souillac',
      'Moka',
    ],
  },
  DZ: {
    africa_llana: [
      'Algiers',
      'Oran',
      'Constantine',
      'Annaba',
      'Blida',
      'Setif',
      'Batna',
      'Tlemcen',
      'Bejaia',
      'Tizi Ouzou',
      'Medea',
      'Bouira',
    ],
  },

  // --- Países sin territorio (caen a FALLBACK, zona `generico`): solo corren su campeonato ----------
  MX: { generico: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Queretaro', 'Toluca'] },
  KZ: { generico: ['Astana', 'Almaty', 'Shymkent', 'Karaganda', 'Aktobe'] },
  UA: { generico: ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv', 'Dnipro', 'Vinnytsia'] },
  BY: { generico: ['Minsk', 'Brest', 'Grodno', 'Gomel', 'Vitebsk', 'Mogilev'] },
  ZA: {
    generico: [
      'Johannesburg',
      'Cape Town',
      'Durban',
      'Pretoria',
      'Stellenbosch',
      'Pietermaritzburg',
    ],
  },
  BR: {
    generico: [
      'Sao Paulo',
      'Rio de Janeiro',
      'Belo Horizonte',
      'Curitiba',
      'Florianopolis',
      'Porto Alegre',
    ],
  },
  RU: { generico: ['Moscow', 'Saint Petersburg', 'Sochi', 'Kazan', 'Yekaterinburg', 'Maykop'] },
  IL: { generico: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Eilat', 'Beersheba'] },
  UY: { generico: ['Montevideo', 'Punta del Este', 'Salto', 'Paysandu', 'Colonia del Sacramento'] },
  PE: { generico: ['Lima', 'Cusco', 'Arequipa', 'Trujillo', 'Huaraz'] },
  CR: { generico: ['San Jose', 'Cartago', 'Alajuela', 'Heredia', 'Liberia'] },
  ER: { generico: ['Asmara', 'Keren', 'Massawa', 'Mendefera', 'Barentu'] },
  IR: { generico: ['Tehran', 'Tabriz', 'Isfahan', 'Shiraz', 'Mashhad'] },
  BO: { generico: ['La Paz', 'Cochabamba', 'Santa Cruz', 'Sucre', 'Oruro'] },
  GE: { generico: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi', 'Gori'] },
  EG: { generico: ['Cairo', 'Alexandria', 'Giza', 'Luxor', 'Aswan'] },
  ET: { generico: ['Addis Ababa', 'Mekele', 'Bahir Dar', 'Gondar', 'Hawassa'] },
  ID: { generico: ['Jakarta', 'Bandung', 'Surabaya', 'Yogyakarta', 'Denpasar'] },
  PH: { generico: ['Manila', 'Quezon City', 'Cebu City', 'Baguio', 'Davao City'] },
  CU: { generico: ['Havana', 'Santiago de Cuba', 'Camaguey', 'Santa Clara', 'Holguin'] },
  PA: { generico: ['Panama City', 'David', 'Colon', 'Santiago de Veraguas', 'Chitre'] },
  MD: { generico: ['Chisinau', 'Balti', 'Cahul', 'Orhei', 'Ungheni'] },
  NG: { generico: ['Lagos', 'Abuja', 'Ibadan', 'Kano', 'Port Harcourt'] },
  KE: { generico: ['Nairobi', 'Eldoret', 'Iten', 'Nakuru', 'Mombasa', 'Kisumu'] },
  TN: { generico: ['Tunis', 'Sfax', 'Sousse', 'Bizerte', 'Kairouan'] },
  VN: { generico: ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hue', 'Da Lat'] },
  AM: { generico: ['Yerevan', 'Gyumri', 'Vanadzor', 'Dilijan', 'Sevan'] },
  IS: { generico: ['Reykjavik', 'Akureyri', 'Selfoss', 'Hafnarfjordur', 'Egilsstadir'] },
  UZ: { generico: ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan', 'Fergana'] },
  // Ciudades-estado y territorios pequeños: sus barrios o localidades con nombre propio.
  SG: { generico: ['Singapore', 'Jurong', 'Tampines', 'Woodlands', 'Changi'] },
  DO: {
    generico: [
      'Santo Domingo',
      'Santiago de los Caballeros',
      'La Vega',
      'Puerto Plata',
      'Jarabacoa',
    ],
  },
  PY: { generico: ['Asuncion', 'Ciudad del Este', 'Encarnacion', 'San Lorenzo', 'Luque'] },
  MK: { generico: ['Skopje', 'Bitola', 'Ohrid', 'Tetovo', 'Strumica'] },
  KG: { generico: ['Bishkek', 'Osh', 'Karakol', 'Cholpon-Ata', 'Naryn'] },
  HK: { generico: ['Hong Kong', 'Kowloon', 'Sha Tin', 'Tai Po', 'Tsuen Wan'] },
  GU: { generico: ['Hagatna', 'Tamuning', 'Dededo', 'Yigo', 'Agat'] },
  BH: { generico: ['Manama', 'Muharraq', 'Riffa', 'Isa Town', 'Sitra'] },
  HN: { generico: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Comayagua', 'Choluteca'] },
  AG: { generico: ['Saint Johns', 'All Saints', 'Liberta', 'English Harbour', 'Codrington'] },
  BB: { generico: ['Bridgetown', 'Speightstown', 'Oistins', 'Holetown', 'Bathsheba'] },
  BM: { generico: ['Hamilton', 'Saint George', 'Somerset', 'Flatts', 'Southampton'] },
  BZ: { generico: ['Belize City', 'Belmopan', 'San Ignacio', 'Orange Walk', 'Dangriga'] },
  CI: { generico: ['Abidjan', 'Yamoussoukro', 'Bouake', 'San-Pedro', 'Korhogo'] },
  CV: { generico: ['Praia', 'Mindelo', 'Santa Maria', 'Assomada', 'Espargos'] },
  DM: { generico: ['Roseau', 'Portsmouth', 'Marigot', 'Grand Bay', 'Castle Bruce'] },
  GW: { generico: ['Bissau', 'Bafata', 'Gabu', 'Cacheu', 'Bolama'] },
  JM: { generico: ['Kingston', 'Montego Bay', 'Spanish Town', 'Ocho Rios', 'Mandeville'] },
  JO: { generico: ['Amman', 'Irbid', 'Aqaba', 'Madaba', 'Jerash'] },
  KY: { generico: ['George Town', 'West Bay', 'Bodden Town', 'East End', 'North Side'] },
  LA: { generico: ['Vientiane', 'Luang Prabang', 'Pakse', 'Savannakhet', 'Vang Vieng'] },
  LB: { generico: ['Beirut', 'Tripoli', 'Sidon', 'Byblos', 'Zahle'] },
  LC: { generico: ['Castries', 'Gros Islet', 'Soufriere', 'Vieux Fort', 'Dennery'] },
  MC: { generico: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'] },
  ME: { generico: ['Podgorica', 'Niksic', 'Budva', 'Kotor', 'Bar', 'Cetinje'] },
  ML: { generico: ['Bamako', 'Sikasso', 'Segou', 'Mopti', 'Kayes'] },
  MN: { generico: ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Kharkhorin', 'Choibalsan'] },
  MO: { generico: ['Macau', 'Taipa', 'Coloane', 'Cotai'] },
  MT: { generico: ['Valletta', 'Mdina', 'Sliema', 'Birkirkara', 'Mosta', 'Victoria'] },
  NA: { generico: ['Windhoek', 'Swakopmund', 'Walvis Bay', 'Otjiwarongo', 'Keetmanshoop'] },
  PR: { generico: ['San Juan', 'Ponce', 'Mayaguez', 'Caguas', 'Arecibo'] },
  SC: { generico: ['Victoria', 'Anse Boileau', 'Beau Vallon', 'Baie Lazare', 'Takamaka'] },
  SN: { generico: ['Dakar', 'Thies', 'Saint-Louis', 'Kaolack', 'Ziguinchor'] },
  SR: { generico: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Albina'] },
  SV: { generico: ['San Salvador', 'Santa Ana', 'San Miguel', 'Sonsonate', 'La Libertad'] },
  SX: { generico: ['Philipsburg', 'Simpson Bay', 'Cul de Sac', 'Cole Bay'] },
  SZ: { generico: ['Mbabane', 'Manzini', 'Lobamba', 'Siteki', 'Nhlangano'] },
  TT: { generico: ['Port of Spain', 'San Fernando', 'Arima', 'Chaguanas', 'Scarborough'] },
  VC: { generico: ['Kingstown', 'Georgetown', 'Barrouallie', 'Layou', 'Chateaubelair'] },
  ZW: { generico: ['Harare', 'Bulawayo', 'Mutare', 'Gweru', 'Masvingo'] },
}

/**
 * Las ciudades de `country` en la zona `zona`; si el país no tiene lista en esa zona, las de todas
 * sus zonas; y `[]` si el país no está en la tabla (el llamador decide: el test garantiza que no pasa
 * con ningún país de `COUNTRIES`).
 */
export function ciudadesDe(country: string, zona: GeoZone): readonly string[] {
  const porZona = CIUDADES[country]
  if (!porZona) return []
  return porZona[zona] ?? Object.values(porZona).flatMap((l) => l ?? [])
}
