/**
 * Recorridos de carrera por ciudades (de dónde a dónde va cada etapa). Los nombres de ciudad son
 * reales (no tienen derechos de autor) y salen de un pool por país anfitrión. El recorrido es
 * determinista por carrera: la misma carrera enseña siempre el mismo trazado, encadenando etapas
 * (el final de una es la salida de la siguiente), como una vuelta de verdad.
 */

/** Ciudades reales por país anfitrión (ISO alpha-2). ASCII, sin duplicados. */
export const CITY_POOLS: Record<string, string[]> = {
  FR: [
    'Paris',
    'Lyon',
    'Marseille',
    'Toulouse',
    'Nice',
    'Nantes',
    'Bordeaux',
    'Lille',
    'Strasbourg',
    'Rennes',
    'Grenoble',
    'Dijon',
    'Montpellier',
    'Nancy',
  ],
  BE: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Bruges',
    'Liege',
    'Namur',
    'Leuven',
    'Mons',
    'Charleroi',
    'Kortrijk',
    'Hasselt',
    'Ostend',
    'Mechelen',
    'Tournai',
  ],
  IT: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Florence',
    'Bologna',
    'Venice',
    'Genoa',
    'Verona',
    'Palermo',
    'Bari',
    'Pisa',
    'Padua',
    'Parma',
  ],
  ES: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Bilbao',
    'Zaragoza',
    'Malaga',
    'Granada',
    'Cordoba',
    'Santander',
    'Pamplona',
    'Valladolid',
    'Vigo',
    'Oviedo',
  ],
  NL: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Maastricht',
    'Nijmegen',
    'Haarlem',
    'Arnhem',
    'Tilburg',
    'Breda',
    'Leiden',
    'Delft',
  ],
  TR: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Antalya',
    'Adana',
    'Konya',
    'Gaziantep',
    'Kayseri',
    'Trabzon',
    'Mersin',
    'Eskisehir',
    'Samsun',
    'Denizli',
  ],
  PT: [
    'Lisbon',
    'Porto',
    'Braga',
    'Coimbra',
    'Faro',
    'Aveiro',
    'Guimaraes',
    'Evora',
    'Setubal',
    'Viseu',
    'Leiria',
    'Cascais',
    'Sintra',
    'Funchal',
  ],
  PL: [
    'Warsaw',
    'Krakow',
    'Lodz',
    'Wroclaw',
    'Poznan',
    'Gdansk',
    'Szczecin',
    'Lublin',
    'Katowice',
    'Bydgoszcz',
    'Torun',
    'Rzeszow',
    'Bialystok',
    'Gdynia',
  ],
  DE: [
    'Berlin',
    'Munich',
    'Hamburg',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Dusseldorf',
    'Dortmund',
    'Leipzig',
    'Dresden',
    'Bremen',
    'Hannover',
    'Nuremberg',
    'Freiburg',
  ],
  GR: [
    'Athens',
    'Thessaloniki',
    'Patras',
    'Heraklion',
    'Larissa',
    'Volos',
    'Ioannina',
    'Kavala',
    'Rhodes',
    'Chania',
    'Kalamata',
    'Sparta',
    'Corinth',
    'Trikala',
  ],
  SI: [
    'Ljubljana',
    'Maribor',
    'Celje',
    'Kranj',
    'Koper',
    'Novo Mesto',
    'Velenje',
    'Ptuj',
    'Nova Gorica',
    'Murska Sobota',
    'Jesenice',
    'Domzale',
    'Kamnik',
    'Skofja Loka',
  ],
  CN: [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Wuhan',
    'Xian',
    'Hangzhou',
    'Nanjing',
    'Chongqing',
    'Tianjin',
    'Suzhou',
    'Qingdao',
    'Kunming',
  ],
  AU: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Canberra',
    'Hobart',
    'Darwin',
    'Geelong',
    'Cairns',
    'Newcastle',
    'Wollongong',
    'Ballarat',
    'Bendigo',
  ],
  HR: [
    'Zagreb',
    'Split',
    'Rijeka',
    'Osijek',
    'Zadar',
    'Dubrovnik',
    'Pula',
    'Varazdin',
    'Sibenik',
    'Karlovac',
    'Sisak',
    'Vukovar',
    'Rovinj',
    'Trogir',
  ],
  DK: [
    'Copenhagen',
    'Aarhus',
    'Odense',
    'Aalborg',
    'Esbjerg',
    'Randers',
    'Kolding',
    'Horsens',
    'Vejle',
    'Roskilde',
    'Helsingor',
    'Silkeborg',
    'Herning',
    'Naestved',
  ],
  JP: [
    'Tokyo',
    'Osaka',
    'Kyoto',
    'Yokohama',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Hiroshima',
    'Sendai',
    'Nara',
    'Nagano',
    'Kanazawa',
    'Nikko',
  ],
  NO: [
    'Oslo',
    'Bergen',
    'Trondheim',
    'Stavanger',
    'Drammen',
    'Tromso',
    'Kristiansand',
    'Bodo',
    'Alesund',
    'Lillehammer',
    'Hamar',
    'Sandnes',
    'Fredrikstad',
    'Molde',
  ],
  CZ: [
    'Prague',
    'Brno',
    'Ostrava',
    'Plzen',
    'Liberec',
    'Olomouc',
    'Ceske Budejovice',
    'Hradec Kralove',
    'Pardubice',
    'Zlin',
    'Kladno',
    'Karlovy Vary',
    'Jihlava',
    'Teplice',
  ],
  CH: [
    'Zurich',
    'Geneva',
    'Basel',
    'Bern',
    'Lausanne',
    'Lucerne',
    'Lugano',
    'St Gallen',
    'Winterthur',
    'Fribourg',
    'Neuchatel',
    'Sion',
    'Davos',
    'Interlaken',
  ],
  US: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Boston',
    'Denver',
    'Seattle',
    'Portland',
    'Austin',
    'Atlanta',
    'Miami',
    'Philadelphia',
    'San Diego',
    'Nashville',
  ],
  AT: [
    'Vienna',
    'Graz',
    'Linz',
    'Salzburg',
    'Innsbruck',
    'Klagenfurt',
    'Villach',
    'Bregenz',
    'Wels',
    'Steyr',
    'Dornbirn',
    'Kitzbuhel',
    'Eisenstadt',
    'Krems',
  ],
  CA: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Winnipeg',
    'Quebec City',
    'Halifax',
    'Victoria',
    'Hamilton',
    'London',
    'Saskatoon',
    'Regina',
  ],
  RO: [
    'Bucharest',
    'Cluj-Napoca',
    'Timisoara',
    'Iasi',
    'Constanta',
    'Brasov',
    'Craiova',
    'Sibiu',
    'Oradea',
    'Ploiesti',
    'Arad',
    'Pitesti',
    'Bacau',
    'Galati',
  ],
  VE: [
    'Caracas',
    'Maracaibo',
    'Valencia',
    'Barquisimeto',
    'Maracay',
    'Ciudad Guayana',
    'Merida',
    'San Cristobal',
    'Maturin',
    'Barcelona',
    'Cumana',
    'Puerto La Cruz',
    'Coro',
    'Barinas',
  ],
  AE: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Al Ain',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
    'Khor Fakkan',
    'Dibba',
    'Kalba',
    'Madinat Zayed',
    'Ruwais',
    'Liwa',
  ],
  CO: [
    'Bogota',
    'Medellin',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Bucaramanga',
    'Pereira',
    'Manizales',
    'Cucuta',
    'Ibague',
    'Santa Marta',
    'Villavicencio',
    'Pasto',
    'Armenia',
  ],
  OM: [
    'Muscat',
    'Salalah',
    'Sohar',
    'Nizwa',
    'Sur',
    'Ibri',
    'Rustaq',
    'Barka',
    'Seeb',
    'Bahla',
    'Khasab',
    'Ibra',
    'Sinaw',
    'Duqm',
  ],
  RS: [
    'Belgrade',
    'Novi Sad',
    'Nis',
    'Kragujevac',
    'Subotica',
    'Zrenjanin',
    'Pancevo',
    'Cacak',
    'Kraljevo',
    'Leskovac',
    'Smederevo',
    'Valjevo',
    'Vranje',
    'Sombor',
  ],
  GB: [
    'London',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Leeds',
    'Bristol',
    'Edinburgh',
    'Glasgow',
    'Cardiff',
    'Newcastle',
    'Sheffield',
    'Nottingham',
    'Cambridge',
    'Oxford',
  ],
  LU: [
    'Luxembourg City',
    'Esch-sur-Alzette',
    'Differdange',
    'Dudelange',
    'Ettelbruck',
    'Diekirch',
    'Wiltz',
    'Echternach',
    'Remich',
    'Grevenmacher',
    'Vianden',
    'Mersch',
    'Clervaux',
    'Bettembourg',
  ],
  LT: [
    'Vilnius',
    'Kaunas',
    'Klaipeda',
    'Siauliai',
    'Panevezys',
    'Alytus',
    'Marijampole',
    'Mazeikiai',
    'Jonava',
    'Utena',
    'Kedainiai',
    'Telsiai',
    'Taurage',
    'Ukmerge',
  ],
  IN: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Chennai',
    'Kolkata',
    'Hyderabad',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Kochi',
    'Lucknow',
    'Nagpur',
    'Surat',
    'Bhopal',
  ],
  SA: [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Taif',
    'Tabuk',
    'Abha',
    'Khobar',
    'Buraydah',
    'Hail',
    'Najran',
    'Jubail',
    'Yanbu',
  ],
  RW: [
    'Kigali',
    'Butare',
    'Gitarama',
    'Ruhengeri',
    'Gisenyi',
    'Byumba',
    'Cyangugu',
    'Kibuye',
    'Nyanza',
    'Rwamagana',
    'Musanze',
    'Huye',
    'Rubavu',
    'Muhanga',
  ],
  CY: [
    'Nicosia',
    'Limassol',
    'Larnaca',
    'Paphos',
    'Famagusta',
    'Kyrenia',
    'Paralimni',
    'Aradippou',
    'Polis',
    'Morphou',
    'Dherynia',
    'Athienou',
    'Lefkara',
    'Kiti',
  ],
  TW: [
    'Taipei',
    'Kaohsiung',
    'Taichung',
    'Tainan',
    'Hsinchu',
    'Keelung',
    'Chiayi',
    'Taoyuan',
    'Changhua',
    'Pingtung',
    'Hualien',
    'Taitung',
    'Yilan',
    'Miaoli',
  ],
  TH: [
    'Bangkok',
    'Chiang Mai',
    'Phuket',
    'Pattaya',
    'Krabi',
    'Ayutthaya',
    'Hua Hin',
    'Nonthaburi',
    'Udon Thani',
    'Khon Kaen',
    'Nakhon Ratchasima',
    'Surat Thani',
    'Rayong',
    'Lampang',
  ],
  BA: [
    'Sarajevo',
    'Banja Luka',
    'Tuzla',
    'Zenica',
    'Mostar',
    'Bihac',
    'Brcko',
    'Bijeljina',
    'Prijedor',
    'Trebinje',
    'Doboj',
    'Gorazde',
    'Livno',
    'Travnik',
  ],
  DZ: [
    'Algiers',
    'Oran',
    'Constantine',
    'Annaba',
    'Blida',
    'Batna',
    'Setif',
    'Djelfa',
    'Biskra',
    'Tlemcen',
    'Bejaia',
    'Tiaret',
    'Ghardaia',
    'Skikda',
  ],
  BJ: [
    'Cotonou',
    'Porto-Novo',
    'Parakou',
    'Djougou',
    'Bohicon',
    'Abomey',
    'Natitingou',
    'Kandi',
    'Ouidah',
    'Lokossa',
    'Save',
    'Come',
    'Malanville',
    'Dassa-Zoume',
  ],
  GT: [
    'Guatemala City',
    'Quetzaltenango',
    'Antigua',
    'Escuintla',
    'Coban',
    'Chichicastenango',
    'Huehuetenango',
    'Mazatenango',
    'Retalhuleu',
    'Solola',
    'Chimaltenango',
    'Jalapa',
    'Jutiapa',
    'Zacapa',
  ],
  AZ: [
    'Baku',
    'Ganja',
    'Sumqayit',
    'Mingachevir',
    'Lankaran',
    'Shaki',
    'Nakhchivan',
    'Shamakhi',
    'Quba',
    'Gabala',
    'Barda',
    'Yevlakh',
    'Naftalan',
    'Goychay',
  ],
  HU: [
    'Budapest',
    'Debrecen',
    'Szeged',
    'Miskolc',
    'Pecs',
    'Gyor',
    'Nyiregyhaza',
    'Kecskemet',
    'Szekesfehervar',
    'Sopron',
    'Eger',
    'Veszprem',
    'Szombathely',
    'Kaposvar',
  ],
  AL: [
    'Tirana',
    'Durres',
    'Vlore',
    'Shkoder',
    'Elbasan',
    'Fier',
    'Korce',
    'Berat',
    'Gjirokaster',
    'Sarande',
    'Lushnje',
    'Kavaje',
    'Pogradec',
    'Kruje',
  ],
  MU: [
    'Port Louis',
    'Curepipe',
    'Quatre Bornes',
    'Vacoas',
    'Beau Bassin',
    'Rose Hill',
    'Mahebourg',
    'Grand Baie',
    'Flacq',
    'Goodlands',
    'Triolet',
    'Souillac',
    'Moka',
    'Pamplemousses',
  ],
  CM: [
    'Yaounde',
    'Douala',
    'Bamenda',
    'Bafoussam',
    'Garoua',
    'Maroua',
    'Ngaoundere',
    'Bertoua',
    'Kribi',
    'Limbe',
    'Buea',
    'Kumba',
    'Ebolowa',
    'Dschang',
  ],
  EE: [
    'Tallinn',
    'Tartu',
    'Narva',
    'Parnu',
    'Kohtla-Jarve',
    'Viljandi',
    'Rakvere',
    'Maardu',
    'Kuressaare',
    'Voru',
    'Valga',
    'Haapsalu',
    'Johvi',
    'Paide',
  ],
  AD: [
    'Andorra la Vella',
    'Escaldes-Engordany',
    'Encamp',
    'Sant Julia de Loria',
    'La Massana',
    'Ordino',
    'Canillo',
    'Arinsal',
    'Pas de la Casa',
    'El Tarter',
    'Soldeu',
    'Santa Coloma',
    'Les Bons',
    'Llorts',
  ],
  BG: [
    'Sofia',
    'Plovdiv',
    'Varna',
    'Burgas',
    'Ruse',
    'Stara Zagora',
    'Pleven',
    'Sliven',
    'Dobrich',
    'Shumen',
    'Pernik',
    'Veliko Tarnovo',
    'Vratsa',
    'Gabrovo',
  ],
  KR: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Ulsan',
    'Suwon',
    'Jeonju',
    'Gyeongju',
    'Jeju',
    'Chuncheon',
    'Gangneung',
    'Pohang',
  ],
  XK: [
    'Pristina',
    'Prizren',
    'Peja',
    'Gjakova',
    'Mitrovica',
    'Ferizaj',
    'Gjilan',
    'Vushtrri',
    'Podujeva',
    'Suhareka',
    'Rahovec',
    'Malisheva',
    'Decan',
    'Istog',
  ],
  EC: [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Ambato',
    'Loja',
    'Manta',
    'Riobamba',
    'Machala',
    'Ibarra',
    'Portoviejo',
    'Esmeraldas',
    'Latacunga',
    'Santo Domingo',
    'Banos',
  ],
  MA: [
    'Casablanca',
    'Rabat',
    'Marrakesh',
    'Fez',
    'Tangier',
    'Agadir',
    'Meknes',
    'Oujda',
    'Kenitra',
    'Tetouan',
    'Essaouira',
    'Ouarzazate',
    'Chefchaouen',
    'El Jadida',
  ],
  SK: [
    'Bratislava',
    'Kosice',
    'Presov',
    'Zilina',
    'Nitra',
    'Banska Bystrica',
    'Trnava',
    'Trencin',
    'Poprad',
    'Martin',
    'Zvolen',
    'Michalovce',
    'Levice',
    'Humenne',
  ],
  MY: [
    'Kuala Lumpur',
    'George Town',
    'Ipoh',
    'Johor Bahru',
    'Malacca',
    'Kota Kinabalu',
    'Kuching',
    'Shah Alam',
    'Petaling Jaya',
    'Seremban',
    'Alor Setar',
    'Kuantan',
    'Miri',
    'Sandakan',
  ],
  BF: [
    'Ouagadougou',
    'Bobo-Dioulasso',
    'Koudougou',
    'Ouahigouya',
    'Banfora',
    'Kaya',
    'Tenkodogo',
    'Dedougou',
    'Fada Ngourma',
    'Dori',
    'Gaoua',
    'Ziniare',
    'Reo',
    'Manga',
  ],
}

/** Hash entero estable de una cadena (para barajar de forma determinista). */
function hashInt(s: string): number {
  let h = 2166136261
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

/** PRNG determinista (mulberry32) a partir de una semilla entera. */
function rng(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * Recorrido de una carrera: una lista de `stops` ciudades del país anfitrión, encadenadas, para que
 * la etapa `i` (1-based) vaya de `route[i-1]` a `route[i]`. Devuelve `stops` nombres (una salida y un
 * final por etapa comparten ciudad). Null si no hay pool para el país o es demasiado pequeño.
 *
 * @param seed  identificador estable de la carrera (mismo trazado siempre).
 * @param country  país anfitrión (ISO alpha-2).
 * @param stages  número de etapas.
 */
export function raceRoute(seed: string, country: string | null, stages: number): string[] | null {
  const pool = country ? CITY_POOLS[country.toUpperCase()] : undefined
  if (!pool || pool.length < 2 || stages < 1) return null
  const need = stages + 1 // una ciudad más que etapas (salida de la 1ª … final de la última)
  const rand = rng(hashInt(seed))
  // Baraja una copia del pool (Fisher-Yates determinista).
  const bag = [...pool]
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[bag[i], bag[j]] = [bag[j]!, bag[i]!]
  }
  const route: string[] = []
  for (let i = 0; i < need; i++) {
    // Si el pool no llega, recicla evitando repetir ciudad consecutiva.
    let city = bag[i % bag.length]!
    if (route.length > 0 && city === route[route.length - 1]) city = bag[(i + 1) % bag.length]!
    route.push(city)
  }
  return route
}

/** De dónde a dónde va una etapa concreta (1-based), o null si no hay recorrido para el país. */
export function stageEndpoints(
  seed: string,
  country: string | null,
  stages: number,
  stageIndex: number,
): { from: string; to: string } | null {
  const route = raceRoute(seed, country, stages)
  if (!route || stageIndex < 1 || stageIndex >= route.length) return null
  return { from: route[stageIndex - 1]!, to: route[stageIndex]! }
}
