/**
 * Países disponibles en el MVP (los que tienen dataset de nombres, Paso 13). Cada uno con su
 * bandera para el selector de creación (SPEC 3.6). El país por IP se preselecciona y es editable.
 */

export interface Country {
  /** Código ISO-3166 alpha-2 en mayúsculas. */
  code: string
  name: string
  flag: string
}

export const COUNTRIES: Country[] = [
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  // Wave 1 of the rollout to all cycling-federation countries (#1), each with a real name pool.
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'CZ', name: 'Czechia', flag: '🇨🇿' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  // Wave 2.
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  // Wave 3.
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  // Wave 4.
  { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  // Wave 5.
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  // Wave 6.
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  // Wave 7.
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  // Wave 8.
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  // Wave 9.
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  // Wave 10 — territorios presentes en el pelotón Continental de referencia.
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  // Wave 11: naciones que albergan carreras del calendario continental (campeonato propio + nombres).
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  // Wave 12: resto de naciones con campeonato nacional (lista real de NC).
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'MO', name: 'Macau', flag: '🇲🇴' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
]

const CODES = new Set(COUNTRIES.map((c) => c.code))

/** ¿Tenemos datos (nombres, selector) para este país? Acepta mayúsculas o minúsculas. */
export function isKnownCountry(code: string): boolean {
  return CODES.has(code.toUpperCase())
}

/**
 * Fallback de país: código ISO NO registrado → país jugable más cercano (cultural/geográfico), por
 * si alguien se conecta desde un país sin representación propia (p.ej. Vaticano→Italia, Nepal→India).
 * Los destinos son siempre países registrados.
 */
export const COUNTRY_FALLBACK: Record<string, string> = {
  LI: 'CH',
  SM: 'IT',
  VA: 'IT',
  GI: 'GB',
  FO: 'DK',
  GL: 'DK',
  AX: 'FI',
  JE: 'GB',
  GG: 'GB',
  IM: 'GB',
  IQ: 'JO',
  SY: 'LB',
  PS: 'JO',
  YE: 'SA',
  KW: 'SA',
  LK: 'IN',
  BD: 'IN',
  NP: 'IN',
  PK: 'IN',
  BT: 'IN',
  MV: 'IN',
  MM: 'TH',
  KH: 'TH',
  BN: 'MY',
  TL: 'ID',
  KP: 'KR',
  TM: 'UZ',
  TJ: 'UZ',
  GH: 'NG',
  SD: 'EG',
  SS: 'EG',
  LY: 'TN',
  AO: 'PT',
  MZ: 'PT',
  CD: 'CM',
  CG: 'CM',
  GA: 'CM',
  TD: 'CM',
  CF: 'CM',
  GN: 'ML',
  SL: 'CI',
  LR: 'CI',
  TG: 'BJ',
  NE: 'ML',
  MR: 'SN',
  GM: 'SN',
  ST: 'CV',
  UG: 'KE',
  TZ: 'KE',
  BI: 'RW',
  ZM: 'ZW',
  MW: 'ZW',
  BW: 'ZA',
  LS: 'ZA',
  MG: 'MU',
  KM: 'MU',
  DJ: 'ET',
  SO: 'ET',
  NI: 'GT',
  HT: 'DO',
  BS: 'JM',
  TC: 'JM',
  AW: 'SX',
  CW: 'SX',
  BQ: 'SX',
  GY: 'TT',
  GD: 'VC',
  KN: 'AG',
  MS: 'AG',
  VG: 'VC',
  VI: 'PR',
  AI: 'SX',
  BL: 'SX',
  MF: 'SX',
  PM: 'CA',
  FK: 'AR',
  GF: 'FR',
  GP: 'FR',
  MQ: 'FR',
  FJ: 'AU',
  PG: 'AU',
  SB: 'AU',
  VU: 'AU',
  NC: 'FR',
  PF: 'FR',
  WS: 'NZ',
  TO: 'NZ',
  KI: 'AU',
  FM: 'GU',
  MH: 'GU',
  PW: 'GU',
  NR: 'AU',
  TV: 'AU',
  CK: 'NZ',
  NU: 'NZ',
  AS: 'GU',
  MP: 'GU',
}

/**
 * Resuelve el país jugable de un código (p.ej. detectado por IP): el propio si está registrado, si
 * no su fallback más cercano, y null si es desconocido (el jugador lo elige a mano).
 */
export function resolveCountry(code: string | null | undefined): string | null {
  if (!code) return null
  const up = code.toUpperCase()
  if (CODES.has(up)) return up
  return COUNTRY_FALLBACK[up] ?? null
}
