/**
 * Recorridos reales por carrera: para cada carrera, la lista de etapas con su localidad de SALIDA y de
 * META (reales). Cada entrada es un par [salida, meta]; una carrera de N etapas tiene N pares. Salida y
 * meta son independientes por etapa: las grandes vueltas tienen TRASLADOS (la meta de una etapa no
 * siempre es la salida de la siguiente), sobre todo tras un día de descanso. Las de un día son un par
 * (circuito: salida = meta en su localidad). Las grandes vueltas y la Volta a Portugal usan su edición
 * real verificada (ver editions.ts); el resto, recorridos reales por región. Nombres ASCII.
 *
 * Invariante (verificado en test): RACE_ROUTES[id].length === nº de etapas de la carrera.
 */
export const RACE_ROUTES: Record<string, [string, string][]> = {
  'race-abruzzo': [
    ['Pescara', 'Vasto'],
    ['Vasto', 'Roccaraso'],
    ['Roccaraso', 'Sulmona'],
    ['Sulmona', 'Blockhaus'],
  ],
  'race-achterhoek': [['Doetinchem', 'Winterswijk']],
  'race-across-flanders': [['Roeselare', 'Waregem']],
  'race-aegean': [['Izmir', 'Selcuk']],
  'race-agostoni': [['Lissone', 'Lissone']],
  'race-ain': [
    ['Bourg-en-Bresse', 'Oyonnax'],
    ['Oyonnax', 'Lelex'],
    ['Lelex', 'Grand Colombier'],
  ],
  'race-alaiye': [['Alanya', 'Manavgat']],
  'race-alanya': [['Alanya', 'Side']],
  'race-albania': [
    ['Tirana', 'Durres'],
    ['Durres', 'Kavaje'],
    ['Kavaje', 'Fier'],
    ['Fier', 'Vlore'],
    ['Vlore', 'Berat'],
  ],
  'race-alentejo': [
    ['Grandola', 'Beja'],
    ['Beja', 'Evora'],
    ['Evora', 'Estremoz'],
    ['Estremoz', 'Portalegre'],
    ['Portalegre', 'Elvas'],
  ],
  'race-algarve': [
    ['Lagos', 'Portimao'],
    ['Portimao', 'Alto da Foia'],
    ['Alto da Foia', 'Tavira'],
    ['Tavira', 'Alto do Malhao'],
    ['Alto do Malhao', 'Alto da Foia'],
  ],
  'race-algeria': [
    ['Algiers', 'Blida'],
    ['Blida', 'Medea'],
    ['Medea', 'Bouira'],
    ['Bouira', 'Setif'],
    ['Setif', 'Setif'],
    ['Setif', 'Constantine'],
  ],
  'race-almeria': [['Almeria', 'Roquetas de Mar']],
  'race-alpes-maritimes': [['Nice', 'Nice']],
  'race-alps': [
    ['Trento', 'Bolzano'],
    ['Bolzano', 'Passo Pordoi'],
    ['Passo Pordoi', 'Cavalese'],
    ['Cavalese', 'Alpe di Pampeago'],
    ['Alpe di Pampeago', 'Plan de Corones'],
  ],
  'race-alsace': [
    ['Strasbourg', 'Colmar'],
    ['Colmar', 'Le Markstein'],
    ['Le Markstein', 'Mulhouse'],
    ['Mulhouse', "Ballon d'Alsace"],
    ["Ballon d'Alsace", 'Grand Ballon'],
  ],
  'race-amstel': [['Maastricht', 'Valkenburg']],
  'race-andalusia': [
    ['Cordoba', 'Baena'],
    ['Baena', 'Alto de Hazallanas'],
    ['Alto de Hazallanas', 'Granada'],
    ['Granada', 'Sierra Nevada'],
    ['Sierra Nevada', 'Alto de Velefique'],
  ],
  'race-andorra-classic': [['Andorra la Vella', 'Arcalis']],
  'race-andratx': [['Andratx', 'Palma']],
  'race-anicolor': [
    ['Aveiro', 'Porto'],
    ['Porto', 'Guimaraes'],
    ['Guimaraes', 'Braga'],
  ],
  'race-annemasse': [['Annemasse', 'Annemasse']],
  'race-antalya': [
    ['Antalya', 'Kemer'],
    ['Kemer', 'Elmali'],
    ['Elmali', 'Korkuteli'],
    ['Korkuteli', 'Serik'],
  ],
  'race-antalya-gp': [['Antalya', 'Side']],
  'race-antwerp': [['Antwerpen', 'Antwerpen']],
  'race-apollon': [['Limassol', 'Larnaca']],
  'race-appennino': [['Novi Ligure', 'Genova']],
  'race-aquitaine': [
    ['Bordeaux', 'Libourne'],
    ['Libourne', 'Bergerac'],
    ['Bergerac', 'Perigueux'],
    ['Perigueux', 'Agen'],
  ],
  'race-arabia': [
    ['Riyadh', 'Diriyah'],
    ['Diriyah', 'Thumamah'],
    ['Thumamah', 'Al Majmaah'],
    ['Al Majmaah', 'Shaqra'],
    ['Shaqra', 'Dawadmi'],
  ],
  'race-arctic': [
    ['Bodo', 'Fauske'],
    ['Fauske', 'Narvik'],
    ['Narvik', 'Harstad'],
    ['Harstad', 'Tromso'],
  ],
  'race-ardeche': [['Guilherand-Granges', 'Aubenas']],
  'race-ardennes': [
    ['Liege', 'Huy'],
    ['Huy', 'Aywaille'],
    ['Aywaille', 'Stavelot'],
    ['Stavelot', 'Spa'],
    ['Spa', 'Liege'],
  ],
  'race-arrabida': [['Setubal', 'Sesimbra']],
  'race-artois': [['Arras', 'Arras']],
  'race-arvedi': [['Cremona', 'Cremona']],
  'race-asturias': [
    ['Oviedo', 'Gijon'],
    ['Gijon', 'Lagos de Covadonga'],
    ['Lagos de Covadonga', 'Alto del Angliru'],
  ],
  'race-aulne': [['Chateaulin', 'Chateaulin']],
  'race-austria': [
    ['Salzburg', 'Zell am See'],
    ['Zell am See', 'Heiligenblut'],
    ['Heiligenblut', 'Sankt Johann im Pongau'],
    ['Sankt Johann im Pongau', 'Bad Gastein'],
    ['Bad Gastein', 'Kitzbuhel'],
  ],
  'race-aveiro': [['Aveiro', 'Ovar']],
  'race-baku': [
    ['Baku', 'Sumqayit'],
    ['Sumqayit', 'Shamakhi'],
    ['Shamakhi', 'Kurdamir'],
    ['Kurdamir', 'Gabala'],
    ['Gabala', 'Ganja'],
  ],
  'race-baltic': [
    ['Klaipeda', 'Palanga'],
    ['Palanga', 'Telsiai'],
    ['Telsiai', 'Kretinga'],
  ],
  'race-basque-country': [
    ['Bilbao', 'Bilbao'],
    ['Pamplona', 'Cuevas de Mendukilo'],
    ['Basauri', 'Basauri'],
    ['Galdakao', 'Galdakao'],
    ['Eibar', 'Eibar'],
    ['Antzuola', 'Bergara'],
  ],
  'race-beauce': [
    ['Sainte-Marie', 'Saint-Georges'],
    ['Saint-Georges', 'Lac-Megantic'],
    ['Lac-Megantic', 'Beauceville'],
    ['Beauceville', 'Saint-Joseph-de-Beauce'],
    ['Saint-Joseph-de-Beauce', 'Saint-Georges'],
  ],
  'race-belgium': [
    ['Antwerpen', 'Gent'],
    ['Gent', 'Geraardsbergen'],
    ['Geraardsbergen', 'Leuven'],
    ['Leuven', 'Huy'],
    ['Huy', 'Namur'],
  ],
  'race-belgrade': [
    ['Belgrade', 'Smederevo'],
    ['Smederevo', 'Pancevo'],
    ['Pancevo', 'Novi Sad'],
    ['Novi Sad', 'Sremski Karlovci'],
  ],
  'race-belvedere': [['Villa Lagarina', 'Villa Lagarina']],
  'race-benelux': [
    ['Diest', 'Diest'],
    ['Blankenberge', 'Ardooie'],
    ['Celles', 'Geraardsbergen'],
    ['Riemst', 'Bilzen-Hoeselt'],
    ['Leuven', 'Leuven'],
  ],
  'race-benin': [
    ['Cotonou', 'Porto-Novo'],
    ['Porto-Novo', 'Dassa-Zoume'],
    ['Dassa-Zoume', 'Parakou'],
    ['Parakou', 'Natitingou'],
    ['Natitingou', 'Djougou'],
  ],
  'race-besancon': [['Besancon', 'Besancon']],
  'race-beskid': [['Bielsko-Biala', 'Szczyrk']],
  'race-beskid-race': [['Zywiec', 'Wisla']],
  'race-besseges': [
    ['Bellegarde', 'Nimes'],
    ['Nimes', 'Besseges'],
    ['Besseges', 'Ales'],
    ['Ales', 'Laudun'],
    ['Laudun', 'La Grande-Motte'],
  ],
  'race-biella': [['Biella', 'Biella']],
  'race-binche': [['Binche', 'Binche']],
  'race-bosnia': [
    ['Mostar', 'Sarajevo'],
    ['Sarajevo', 'Jahorina'],
    ['Jahorina', 'Bjelasnica'],
  ],
  'race-braakman': [['Terneuzen', 'Terneuzen']],
  'race-brabant': [['Leuven', 'Overijse']],
  'race-brda': [['Nova Gorica', 'Dobrovo']],
  'race-bredene': [['Bredene', 'Koksijde']],
  'race-bretagne': [
    ['Saint-Brieuc', 'Loudeac'],
    ['Loudeac', 'Carhaix'],
    ['Carhaix', 'Quimper'],
    ['Quimper', 'Lorient'],
    ['Lorient', 'Pontivy'],
    ['Pontivy', 'Pontivy'],
    ['Pontivy', 'Vannes'],
  ],
  'race-britain': [
    ['Sheffield', 'Barnsley'],
    ['Barnsley', 'Holmfirth'],
    ['Holmfirth', 'Huddersfield'],
    ['Huddersfield', 'Hebden Bridge'],
    ['Hebden Bridge', 'Halifax'],
  ],
  'race-brittany': [['Rennes', 'Rennes']],
  'race-bruges': [['Brugge', 'De Panne']],
  'race-brussels': [['Brussel', 'Brussel']],
  'race-bulgaria': [
    ['Sofia', 'Plovdiv'],
    ['Plovdiv', 'Karlovo'],
    ['Karlovo', 'Kazanlak'],
    ['Kazanlak', 'Sliven'],
    ['Sliven', 'Yambol'],
    ['Yambol', 'Burgas'],
  ],
  'race-burgos': [
    ['Burgos', 'Lerma'],
    ['Lerma', 'Lagunas de Neila'],
    ['Lagunas de Neila', 'Salas de los Infantes'],
    ['Salas de los Infantes', 'Picon Blanco'],
    ['Picon Blanco', 'Burgos'],
  ],
  'race-calvia': [['Calvia', 'Palma']],
  'race-camembert': [['Camembert', 'Vimoutiers']],
  'race-cameroon': [
    ['Yaounde', 'Douala'],
    ['Douala', 'Bafoussam'],
    ['Bafoussam', 'Foumban'],
    ['Foumban', 'Dschang'],
    ['Dschang', 'Bafang'],
    ['Bafang', 'Bamenda'],
    ['Bamenda', 'Bamenda'],
    ['Bamenda', 'Bafoussam'],
  ],
  'race-castellon': [['Castellon', 'Valencia']],
  'race-castilla-leon': [['Valladolid', 'Segovia']],
  'race-catalonia': [
    ['Sant Feliu de Guixols', 'Sant Feliu de Guixols'],
    ['Figueres', 'Banyoles'],
    ['Mont-roig del Camp', 'Vila-seca'],
    ['Mataro', 'Vallter 2000'],
    ["La Seu d'Urgell", 'Coll de Pal'],
    ['Berga', 'Queralt'],
    ['Barcelona', 'Barcelona'],
  ],
  'race-cerami': [['Quaregnon', 'Frameries']],
  'race-chauny': [['Chauny', 'Chauny']],
  'race-cholet': [['Cholet', 'Cholet']],
  'race-chrono': [['Les Herbiers', 'Les Herbiers']],
  'race-colombia': [
    ['Medellin', 'Rionegro'],
    ['Rionegro', 'La Union'],
    ['La Union', 'El Carmen de Viboral'],
    ['El Carmen de Viboral', 'El Retiro'],
    ['El Retiro', 'Rionegro'],
    ['Rionegro', 'Medellin'],
  ],
  'race-colombia-tour': [
    ['Medellin', 'Rionegro'],
    ['Rionegro', 'La Union'],
    ['La Union', 'Sonson'],
    ['Sonson', 'Abejorral'],
    ['Abejorral', 'Santa Barbara'],
    ['Santa Barbara', 'Alto de Minas'],
    ['Alto de Minas', 'Amaga'],
    ['Amaga', 'Caldas'],
    ['Caldas', 'Medellin'],
  ],
  'race-communes': [['Mons', 'La Louviere']],
  'race-copenhagen': [['Copenhagen', 'Copenhagen']],
  'race-criquielion': [['Lessines', 'Lessines']],
  'race-croatia': [
    ['Rijeka', 'Crikvenica'],
    ['Crikvenica', 'Ucka'],
    ['Ucka', 'Opatija'],
    ['Opatija', 'Platak'],
    ['Platak', 'Delnice'],
    ['Delnice', 'Sljeme'],
  ],
  'race-czechia': [
    ['Brno', 'Vyskov'],
    ['Vyskov', 'Blansko'],
    ['Blansko', 'Boskovice'],
    ['Boskovice', 'Brno'],
  ],
  'race-denain': [['Denain', 'Denain']],
  'race-denmark': [
    ['Copenhagen', 'Nyborg'],
    ['Nyborg', 'Vejle'],
    ['Vejle', 'Kolding'],
    ['Kolding', 'Silkeborg'],
    ['Silkeborg', 'Aarhus'],
  ],
  'race-dodecanese': [['Lindos', 'Rhodes']],
  'race-doubs': [['Pontarlier', 'Pontarlier']],
  'race-down-under': [
    ['Adelaide', 'Adelaide'],
    ['Tanunda', 'Tanunda'],
    ['Norwood', 'Uraidla'],
    ['Henley Beach', 'Nairne'],
    ['Brighton', 'Willunga'],
    ['Stirling', 'Stirling'],
  ],
  'race-drome': [['Valence', 'Valence']],
  'race-dunkerque': [['Dunkerque', 'Dunkerque']],
  'race-ebre': [['Tortosa', 'Gandesa']],
  'race-ecuador': [
    ['Quito', 'Latacunga'],
    ['Latacunga', 'Zumbahua'],
    ['Zumbahua', 'Ambato'],
    ['Ambato', 'Riobamba'],
    ['Riobamba', 'Guano'],
    ['Guano', 'Banos'],
  ],
  'race-elfsteden': [['Bolsward', 'Bolsward']],
  'race-emilia': [['Carpi', 'Bologna']],
  'race-emilia-gp': [['Reggio Emilia', 'Modena']],
  'race-emirates': [
    ['Madinat Zayed', 'Liwa'],
    ['Al Hudayriat Island', 'Al Hudayriat Island'],
    ['Umm Al Quwain', 'Jebel Mobrah'],
    ['Fujairah', 'Fujairah'],
    ['Dubai', 'Hamdan Bin Mohammed Smart University'],
    ['Al Ain', 'Jebel Hafeet'],
    ['Abu Dhabi', 'Abu Dhabi'],
  ],
  'race-estonia': [
    ['Tallinn', 'Parnu'],
    ['Parnu', 'Viljandi'],
    ['Viljandi', 'Tartu'],
  ],
  'race-estrela': [
    ['Guarda', 'Covilha'],
    ['Covilha', 'Torre'],
    ['Torre', 'Penhas da Saude'],
  ],
  'race-euro-champs': [['Plumelec', 'Plumelec']],
  'race-fagnes': [['Eupen', 'Malmedy']],
  'race-famenne': [['Marche-en-Famenne', 'Marche-en-Famenne']],
  'race-faso': [
    ['Ouagadougou', 'Koudougou'],
    ['Koudougou', 'Bobo-Dioulasso'],
    ['Bobo-Dioulasso', 'Banfora'],
    ['Banfora', 'Sindou'],
    ['Sindou', 'Bobo-Dioulasso'],
  ],
  'race-figueira': [['Figueira da Foz', 'Montemor-o-Velho']],
  'race-finistere': [['Quimper', 'Quimper']],
  'race-flanders': [['Antwerpen', 'Oudenaarde']],
  'race-flandrien': [['Zottegem', 'Oudenaarde']],
  'race-fleche-ardennaise': [['Malmedy', 'Aywaille']],
  'race-fleche-sud': [
    ['Esch-sur-Alzette', 'Dudelange'],
    ['Dudelange', 'Rumelange'],
    ['Rumelange', 'Differdange'],
    ['Differdange', 'Petange'],
    ['Petange', 'Esch-sur-Alzette'],
  ],
  'race-fourmies': [['Fourmies', 'Fourmies']],
  'race-france': [
    ['Barcelona', 'Barcelona'],
    ['Tarragona', 'Barcelona'],
    ['Granollers', 'Les Angles'],
    ['Carcassonne', 'Foix'],
    ['Lannemezan', 'Pau'],
    ['Pau', 'Gavarnie-Gedre'],
    ['Hagetmau', 'Bordeaux'],
    ['Perigueux', 'Bergerac'],
    ['Malemort', 'Ussel'],
    ['Aurillac', 'Le Lioran'],
    ['Vichy', 'Nevers'],
    ['Magny-Cours', 'Chalon-sur-Saone'],
    ['Dole', 'Belfort'],
    ['Mulhouse', 'Le Markstein'],
    ['Champagnole', 'Plateau de Solaison'],
    ['Evian-les-Bains', 'Thonon-les-Bains'],
    ['Chambery', 'Voiron'],
    ['Voiron', 'Orcieres-Merlette'],
    ['Gap', "Alpe d'Huez"],
    ["Le Bourg-d'Oisans", "Alpe d'Huez"],
    ['Thoiry', 'Paris'],
  ],
  'race-franco-belgian': [['Lille', 'Roubaix']],
  'race-frankfurt': [['Eschborn', 'Frankfurt']],
  'race-friuli': [
    ['Pordenone', 'Udine'],
    ['Udine', 'Cividale del Friuli'],
    ['Cividale del Friuli', 'Gorizia'],
    ['Gorizia', 'Trieste'],
  ],
  'race-funen': [['Odense', 'Odense']],
  'race-galicia': [
    ['A Coruna', 'Santiago de Compostela'],
    ['Santiago de Compostela', 'Ezaro'],
    ['Ezaro', 'Pontevedra'],
    ['Pontevedra', 'Manzaneda'],
  ],
  'race-germany': [
    ['Stuttgart', 'Karlsruhe'],
    ['Karlsruhe', 'Baden-Baden'],
    ['Baden-Baden', 'Offenburg'],
    ['Offenburg', 'Freiburg'],
    ['Freiburg', 'Lorrach'],
  ],
  'race-getxo': [['Getxo', 'Getxo']],
  'race-gila': [
    ['Silver City', 'Hurley'],
    ['Hurley', 'Mogollon'],
    ['Mogollon', 'Pinos Altos'],
    ['Pinos Altos', 'Lake Roberts'],
    ['Lake Roberts', 'Silver City'],
  ],
  'race-gippingen': [['Baden', 'Bad Zurzach']],
  'race-gooik': [['Gooik', 'Gooik']],
  'race-great-ocean': [['Torquay', 'Torquay']],
  'race-guangxi': [
    ['Fangchenggang', 'Fangchenggang'],
    ['Chongzuo', 'Jingxi'],
    ['Jingxi', 'Bama'],
    ['Bama', 'Jinchengjiang'],
    ['Yizhou', 'Nongla'],
    ['Nanning', 'Nanning'],
  ],
  'race-guatemala': [
    ['Guatemala City', 'Escuintla'],
    ['Escuintla', 'Antigua'],
    ['Antigua', 'Chimaltenango'],
    ['Chimaltenango', 'Tecpan'],
    ['Tecpan', 'Quetzaltenango'],
  ],
  'race-hainan': [
    ['Haikou', 'Wenchang'],
    ['Wenchang', 'Qionghai'],
    ['Qionghai', 'Wanning'],
    ['Wanning', 'Wuzhishan'],
    ['Wuzhishan', 'Sanya'],
  ],
  'race-halle': [['Halle', 'Ingooigem']],
  'race-hamburg': [['Buxtehude', 'Hamburg']],
  'race-harelbeke': [['Harelbeke', 'Harelbeke']],
  'race-hauts-de-france': [
    ['Amiens', 'Arras'],
    ['Arras', 'Lille'],
    ['Lille', 'Valenciennes'],
    ['Valenciennes', 'Cambrai'],
    ['Cambrai', 'Saint-Quentin'],
  ],
  'race-heist': [['Heist-op-den-Berg', 'Heist-op-den-Berg']],
  'race-hellas': [
    ['Athens', 'Thebes'],
    ['Thebes', 'Livadia'],
    ['Livadia', 'Delphi'],
    ['Delphi', 'Arachova'],
    ['Arachova', 'Lamia'],
  ],
  'race-herning': [['Herning', 'Herning']],
  'race-holland': [
    ['Amsterdam', 'Utrecht'],
    ['Utrecht', 'Arnhem'],
    ['Arnhem', 'Venlo'],
    ['Venlo', 'Valkenburg'],
    ['Valkenburg', 'Sittard'],
    ['Sittard', 'Maastricht'],
  ],
  'race-houtland': [['Torhout', 'Lichtervelde']],
  'race-hungary': [
    ['Budapest', 'Szekesfehervar'],
    ['Szekesfehervar', 'Veszprem'],
    ['Veszprem', 'Kaposvar'],
    ['Kaposvar', 'Pecs'],
    ['Pecs', 'Szekszard'],
  ],
  'race-huy': [['Charleroi', 'Huy']],
  'race-isbergues': [['Isbergues', 'Isbergues']],
  'race-isere': [
    ['Vienne', 'Grenoble'],
    ['Grenoble', 'Chamrousse'],
    ['Chamrousse', 'Villard-de-Lans'],
    ['Villard-de-Lans', "Alpe d'Huez"],
    ["Alpe d'Huez", 'Les Deux Alpes'],
  ],
  'race-istanbul': [
    ['Istanbul', 'Gebze'],
    ['Gebze', 'Kartepe'],
    ['Kartepe', 'Sapanca'],
    ['Sapanca', 'Adapazari'],
  ],
  'race-istria': [
    ['Pula', 'Rovinj'],
    ['Rovinj', 'Porec'],
    ['Porec', 'Umag'],
    ['Umag', 'Pazin'],
  ],
  'race-italy': [
    ['Nessebar', 'Burgas'],
    ['Burgas', 'Veliko Tarnovo'],
    ['Plovdiv', 'Sofia'],
    ['Catanzaro', 'Cosenza'],
    ['Praia a Mare', 'Potenza'],
    ['Paestum', 'Napoli'],
    ['Formia', 'Blockhaus'],
    ['Chieti', 'Fermo'],
    ['Cervia', 'Corno alle Scale'],
    ['Viareggio', 'Massa'],
    ['Porcari', 'Chiavari'],
    ['Imperia', 'Novi Ligure'],
    ['Alessandria', 'Verbania'],
    ['Aosta', 'Pila'],
    ['Voghera', 'Milano'],
    ['Bellinzona', 'Cari'],
    ["Cassano d'Adda", 'Andalo'],
    ['Fai della Paganella', 'Pieve di Soligo'],
    ['Feltre', 'Piani di Pezze'],
    ['Gemona del Friuli', 'Piancavallo'],
    ['Roma', 'Roma'],
  ],
  'race-jaen': [['Ubeda', 'Jaen']],
  'race-japan': [['Kyoto', 'Kyoto']],
  'race-jura': [['Lons-le-Saunier', 'Les Rousses']],
  'race-kempen': [['Herentals', 'Turnhout']],
  'race-koln': [['Koln', 'Bonn']],
  'race-korea': [
    ['Seoul', 'Chungju'],
    ['Chungju', 'Mungyeong'],
    ['Mungyeong', 'Andong'],
    ['Andong', 'Yeongju'],
    ['Yeongju', 'Danyang'],
  ],
  'race-kosovo': [
    ['Pristina', 'Ferizaj'],
    ['Ferizaj', 'Prizren'],
    ['Prizren', 'Gjakova'],
    ['Gjakova', 'Peja'],
  ],
  'race-kranj': [['Kranj', 'Trzic']],
  'race-kreiz-breizh': [
    ['Rostrenen', 'Carhaix'],
    ['Carhaix', 'Mur-de-Bretagne'],
    ['Mur-de-Bretagne', 'Gouarec'],
    ['Gouarec', 'Callac'],
  ],
  'race-kumano': [
    ['Kumano', 'Nachikatsuura'],
    ['Nachikatsuura', 'Hongu'],
    ['Hongu', 'Shingu'],
    ['Shingu', 'Kumano'],
  ],
  'race-kuurne': [['Kuurne', 'Kuurne']],
  'race-kyushu': [
    ['Fukuoka', 'Hita'],
    ['Hita', 'Kokonoe'],
    ['Kokonoe', 'Beppu'],
  ],
  'race-laigueglia': [['Laigueglia', 'Laigueglia']],
  'race-langkawi': [
    ['Langkawi', 'Kangar'],
    ['Kangar', 'Sungai Petani'],
    ['Sungai Petani', 'Ipoh'],
    ['Ipoh', 'Cameron Highlands'],
    ['Cameron Highlands', 'Kuala Kubu Bharu'],
    ['Kuala Kubu Bharu', 'Genting Highlands'],
    ['Genting Highlands', 'Kuala Lumpur'],
    ['Kuala Lumpur', 'Melaka'],
  ],
  'race-lazio': [['Frosinone', 'Roma']],
  'race-legnano': [['Legnano', 'Legnano']],
  'race-leon': [['Leon', 'Leon']],
  'race-liberazione': [['Roma', 'Roma']],
  'race-liege': [['Liege', 'Liege']],
  'race-liege-espoirs': [['Bastogne', 'Liege']],
  'race-lillers': [['Lillers', 'Lillers']],
  'race-limburg': [['Maastricht', 'Valkenburg']],
  'race-limousin': [
    ['Limoges', 'Saint-Yrieix-la-Perche'],
    ['Saint-Yrieix-la-Perche', 'Brive-la-Gaillarde'],
    ['Brive-la-Gaillarde', 'Tulle'],
    ['Tulle', 'Gueret'],
  ],
  'race-lithuania': [
    ['Vilnius', 'Trakai'],
    ['Trakai', 'Alytus'],
    ['Alytus', 'Druskininkai'],
    ['Druskininkai', 'Kaunas'],
    ['Kaunas', 'Kedainiai'],
  ],
  'race-loir-cher': [
    ['Blois', 'Vendome'],
    ['Vendome', 'Montoire-sur-le-Loir'],
    ['Montoire-sur-le-Loir', 'Romorantin-Lanthenay'],
    ['Romorantin-Lanthenay', 'Salbris'],
    ['Salbris', 'Blois'],
  ],
  'race-loire': [
    ['Roanne', 'Feurs'],
    ['Feurs', 'Saint-Etienne'],
    ['Saint-Etienne', 'Montbrison'],
    ['Montbrison', 'Charlieu'],
  ],
  'race-loire-atlantique': [['Nantes', 'Saint-Nazaire']],
  'race-lombardy': [['Bergamo', 'Como']],
  'race-luxembourg': [
    ['Esch-sur-Alzette', 'Dudelange'],
    ['Dudelange', 'Diekirch'],
    ['Diekirch', 'Echternach'],
    ['Echternach', 'Wiltz'],
    ['Wiltz', 'Luxembourg'],
  ],
  'race-lyon': [
    ['Lyon', 'Villefranche-sur-Saone'],
    ['Villefranche-sur-Saone', 'Chiroubles'],
    ['Chiroubles', 'Yzeron'],
  ],
  'race-magna-grecia': [
    ['Sibari', 'Crotone'],
    ['Crotone', 'Camigliatello Silano'],
    ['Camigliatello Silano', 'Gambarie'],
  ],
  'race-malopolska': [
    ['Krakow', 'Tarnow'],
    ['Tarnow', 'Nowy Sacz'],
    ['Nowy Sacz', 'Krakow'],
  ],
  'race-maras': [
    ['Kahramanmaras', 'Gaziantep'],
    ['Gaziantep', 'Islahiye'],
    ['Islahiye', 'Osmaniye'],
    ['Osmaniye', 'Adana'],
  ],
  'race-marseille': [['Marseille', 'Marseille']],
  'race-maryland': [
    ['Baltimore', 'Frederick'],
    ['Frederick', 'Cumberland'],
    ['Cumberland', 'Hagerstown'],
  ],
  'race-matteotti': [['Pescara', 'Pescara']],
  'race-mauritius': [
    ['Port Louis', 'Grand Baie'],
    ['Grand Baie', 'Curepipe'],
    ['Curepipe', 'Mahebourg'],
    ['Mahebourg', 'Port Louis'],
  ],
  'race-mayenne': [
    ['Laval', 'Mayenne'],
    ['Mayenne', 'Ernee'],
    ['Ernee', 'Chateau-Gontier'],
    ['Chateau-Gontier', 'Laval'],
  ],
  'race-mazury': [
    ['Olsztyn', 'Mragowo'],
    ['Mragowo', 'Gizycko'],
    ['Gizycko', 'Elk'],
  ],
  'race-mercantour': [['Nice', 'Isola 2000']],
  'race-mersin': [
    ['Mersin', 'Erdemli'],
    ['Erdemli', 'Silifke'],
    ['Silifke', 'Tarsus'],
    ['Tarsus', 'Adana'],
  ],
  'race-mirabelle': [['Nancy', 'Nancy']],
  'race-monsere': [['Roeselare', 'Hooglede']],
  'race-montreal': [['Montreal', 'Montreal']],
  'race-morbihan': [['Grand-Champ', 'Grand-Champ']],
  'race-morocco': [
    ['Casablanca', 'Marrakesh'],
    ['Marrakesh', 'Asni'],
    ['Asni', 'Amizmiz'],
    ['Amizmiz', 'Setti Fatma'],
    ['Setti Fatma', 'Tahannaout'],
    ['Tahannaout', 'Oukaimeden'],
    ['Oukaimeden', 'Oukaimeden'],
    ['Oukaimeden', 'Asni'],
  ],
  'race-morvedre': [['Sagunto', 'Segorbe']],
  'race-munster': [['Munster', 'Telgte']],
  'race-murcia': [
    ['Murcia', 'Cartagena'],
    ['Cartagena', 'Alhama de Murcia'],
  ],
  'race-muscat': [['Muscat', 'Barka']],
  'race-muur': [['Ninove', 'Geraardsbergen']],
  'race-namur': [['Namur', 'Namur']],
  'race-navarre': [['Estella', 'Pamplona']],
  'race-nippon': [
    ['Shizuoka', 'Numazu'],
    ['Numazu', 'Izu'],
    ['Izu', 'Ito'],
    ['Ito', 'Hakone'],
    ['Hakone', 'Gotemba'],
    ['Gotemba', 'Fujiyoshida'],
    ['Fujiyoshida', 'Yamanakako'],
    ['Yamanakako', 'Fujinomiya'],
  ],
  'race-nokere': [['Deinze', 'Nokere']],
  'race-norway': [
    ['Oslo', 'Drammen'],
    ['Drammen', 'Norefjell'],
    ['Norefjell', 'Honefoss'],
    ['Honefoss', 'Oslo'],
  ],
  'race-novo-mesto': [['Novo Mesto', 'Otocec']],
  'race-nxt': [['Emmen', 'Hoogeveen']],
  'race-oberosterreich': [
    ['Linz', 'Wels'],
    ['Wels', 'Steyr'],
    ['Steyr', 'Enns'],
    ['Enns', 'Linz'],
  ],
  'race-occitanie': [
    ['Auch', 'Toulouse'],
    ['Toulouse', 'Luz Ardiden'],
    ['Luz Ardiden', 'Tarbes'],
    ['Tarbes', 'Peyragudes'],
  ],
  'race-oise': [
    ['Beauvais', 'Clermont'],
    ['Clermont', 'Senlis'],
    ['Senlis', 'Compiegne'],
    ['Compiegne', 'Noyon'],
  ],
  'race-olympia': [
    ['Apeldoorn', 'Nijmegen'],
    ['Nijmegen', 'Arnhem'],
    ['Arnhem', 'Venlo'],
    ['Venlo', 'Valkenburg'],
    ['Valkenburg', 'Maastricht'],
  ],
  'race-oman': [
    ['Muscat', 'Nizwa'],
    ['Nizwa', 'Jabal Al Akhdar'],
    ['Jabal Al Akhdar', 'Al Hamra'],
    ['Al Hamra', 'Jabal Shams'],
    ['Jabal Shams', 'Al Amerat'],
  ],
  'race-ontur': [['Ontur', 'Hellin']],
  'race-opening-classic': [['Gent', 'Ninove']],
  'race-ordizia': [['Ordizia', 'Ordizia']],
  'race-oropa': [['Biella', 'Oropa']],
  'race-overijssel': [['Rijssen', 'Rijssen']],
  'race-palma': [['Palma', 'Palma']],
  'race-pantani': [['Cesenatico', 'Monte Carpegna']],
  'race-pascua': [['Estella', 'Estella']],
  'race-peccioli': [['Peccioli', 'Peccioli']],
  'race-pedalia': [['Marathon', 'Athens']],
  'race-philadelphia': [['Philadelphia', 'Philadelphia']],
  'race-piedmont': [['Omegna', 'Torino']],
  'race-piva': [['Farra di Soligo', 'Farra di Soligo']],
  'race-plouay': [['Plouay', 'Plouay']],
  'race-poland': [
    ['Gdynia', 'Koszalin'],
    ['Miedzyzdroje', 'Szczecin'],
    ['Gorzow Wielkopolski', 'Zielona Gora'],
    ['Zagan', 'Karpacz'],
    ['Opole', 'Kocierz Resort'],
    ['Bukovina Resort', 'Bukowina Tatrzanska'],
    ['Wieliczka', 'Wieliczka'],
  ],
  'race-polynormande': [['Saint-Martin-de-Landelles', 'Saint-Martin-de-Landelles']],
  'race-popolarissima': [['Treviso', 'Treviso']],
  'race-porec': [['Motovun', 'Porec']],
  'race-portugal': [
    ['Maia', 'Maia'],
    ['Viana do Castelo', 'Braga'],
    ['Felgueiras', 'Fafe'],
    ['Boticas', 'Braganca'],
    ['Braganca', 'Mondim de Basto'],
    ['Lamego', 'Viseu'],
    ['Agueda', 'Guarda'],
    ['Sabugal', 'Covilha'],
    ['Ferreira do Zezere', 'Santarem'],
    ['Alcobaca', 'Alto de Montejunto'],
    ['Lisboa', 'Lisboa'],
  ],
  'race-poyang': [
    ['Nanchang', 'Jiujiang'],
    ['Jiujiang', 'Lushan'],
    ['Lushan', 'Jingdezhen'],
    ['Jingdezhen', 'Wuyuan'],
    ['Wuyuan', 'Shangrao'],
    ['Shangrao', 'Poyang'],
  ],
  'race-prato': [['Prato', 'Prato']],
  'race-provence': [
    ['Marseille', 'Salon-de-Provence'],
    ['Salon-de-Provence', 'Montagne de Lure'],
    ['Montagne de Lure', 'Chalet Reynard'],
  ],
  'race-pune': [
    ['Pune', 'Lonavala'],
    ['Lonavala', 'Lavasa'],
    ['Lavasa', 'Panchgani'],
    ['Panchgani', 'Mahabaleshwar'],
    ['Mahabaleshwar', 'Sinhagad'],
  ],
  'race-qinghai': [
    ['Xining', 'Huangyuan'],
    ['Huangyuan', 'Gonghe'],
    ['Gonghe', 'Chaka'],
    ['Chaka', 'Heimahe'],
    ['Heimahe', 'Gangcha'],
    ['Gangcha', 'Haiyan'],
    ['Haiyan', 'Xihai'],
    ['Xihai', 'Menyuan'],
  ],
  'race-quebec': [['Quebec City', 'Quebec City']],
  'race-recioto': [['Negrar', 'Negrar']],
  'race-reggio': [['Reggio Emilia', 'Reggio Emilia']],
  'race-rhodes': [
    ['Rhodes', 'Faliraki'],
    ['Faliraki', 'Archangelos'],
    ['Archangelos', 'Lindos'],
    ['Lindos', 'Ialysos'],
  ],
  'race-rhodes-gp': [['Rhodes', 'Lindos']],
  'race-rhone-alpes': [
    ['Vizille', 'Saint-Ismier'],
    ['Saint-Martin-le-Vinoux', 'Le Puy-en-Velay'],
    ['Perreux', 'Perreux'],
    ['Le Puy-en-Velay', 'Montrond-les-Bains'],
    ['Saint-Chamond', 'Villars-les-Dombes'],
    ['Saint-Vulbas', 'Crest-Voland'],
    ['La Bridoire', 'Grand Colombier'],
    ['Beaufort', 'Plateau de Solaison'],
  ],
  'race-ringerike': [['Honefoss', 'Honefoss']],
  'race-romagna': [
    ['Rimini', 'Cesenatico'],
    ['Cesenatico', 'Cesena'],
    ['Cesena', 'Forli'],
    ['Forli', 'Faenza'],
    ['Faenza', 'Imola'],
  ],
  'race-romagna-giro': [['Lugo', 'Faenza']],
  'race-romandy': [
    ['Villars-sur-Glane', 'Villars-sur-Glane'],
    ['Martigny', 'Martigny'],
    ['Rue', 'Vucherens'],
    ['Orbe', 'Orbe'],
    ['Broc', 'Charmey'],
    ['Lucens', 'Leysin'],
  ],
  'race-romania': [
    ['Cluj-Napoca', 'Targu Mures'],
    ['Targu Mures', 'Sighisoara'],
    ['Sighisoara', 'Medias'],
    ['Medias', 'Sibiu'],
    ['Sibiu', 'Alba Iulia'],
  ],
  'race-roubaix': [['Compiegne', 'Roubaix']],
  'race-roubaix-espoirs': [['Bohain-en-Vermandois', 'Roubaix']],
  'race-rucphen': [['Roosendaal', 'Rucphen']],
  'race-rutland': [['Oakham', 'Oakham']],
  'race-rwanda': [
    ['Kigali', 'Huye'],
    ['Huye', 'Rusizi'],
    ['Rusizi', 'Karongi'],
    ['Karongi', 'Rubavu'],
    ['Rubavu', 'Musanze'],
    ['Musanze', 'Muhanga'],
    ['Muhanga', 'Kigali'],
    ['Kigali', 'Kigali'],
  ],
  'race-samsun': [
    ['Samsun', 'Carsamba'],
    ['Carsamba', 'Unye'],
    ['Unye', 'Fatsa'],
    ['Fatsa', 'Ordu'],
  ],
  'race-samyn': [['Quaregnon', 'Dour']],
  'race-san-daniele': [['San Daniele del Friuli', 'San Daniele del Friuli']],
  'race-san-sebastian': [['San Sebastian', 'San Sebastian']],
  'race-sanremo': [['Milano', 'Sanremo']],
  'race-sardegna': [
    ['Cagliari', 'Sassari'],
    ['Sassari', 'Alghero'],
    ['Alghero', 'Olbia'],
    ['Olbia', 'Nuoro'],
    ['Nuoro', 'Cagliari'],
  ],
  'race-sauerland': [
    ['Arnsberg', 'Meschede'],
    ['Meschede', 'Winterberg'],
    ['Winterberg', 'Brilon'],
    ['Brilon', 'Arnsberg'],
  ],
  'race-schelde': [['Antwerpen', 'Schoten']],
  'race-serbie': [
    ['Belgrade', 'Kragujevac'],
    ['Kragujevac', 'Kraljevo'],
    ['Kraljevo', 'Cacak'],
    ['Cacak', 'Uzice'],
  ],
  'race-ses-salines': [['Ses Salines', 'Sa Calobra']],
  'race-sharjah': [
    ['Sharjah', 'Ajman'],
    ['Ajman', 'Ras Al Khaimah'],
    ['Ras Al Khaimah', 'Dibba'],
    ['Dibba', 'Khor Fakkan'],
    ['Khor Fakkan', 'Fujairah'],
  ],
  'race-sibiu': [
    ['Sibiu', 'Medias'],
    ['Medias', 'Paltinis'],
    ['Paltinis', 'Fagaras'],
    ['Fagaras', 'Balea Lac'],
  ],
  'race-slezanski': [['Wroclaw', 'Sobotka']],
  'race-slovakia': [
    ['Bratislava', 'Trnava'],
    ['Trnava', 'Nitra'],
    ['Nitra', 'Banska Bystrica'],
    ['Banska Bystrica', 'Poprad'],
    ['Poprad', 'Kosice'],
  ],
  'race-slovenia': [
    ['Ljubljana', 'Maribor'],
    ['Maribor', 'Rogla'],
    ['Rogla', 'Celje'],
    ['Celje', 'Velika Planina'],
    ['Velika Planina', 'Kranjska Gora'],
  ],
  'race-slovenian-istria': [['Koper', 'Piran']],
  'race-solidarnosc': [
    ['Lodz', 'Piotrkow Trybunalski'],
    ['Piotrkow Trybunalski', 'Czestochowa'],
    ['Czestochowa', 'Radomsko'],
    ['Radomsko', 'Lodz'],
  ],
  'race-somme': [['Amiens', 'Amiens']],
  'race-south-bohemia': [
    ['Ceske Budejovice', 'Tabor'],
    ['Tabor', 'Jindrichuv Hradec'],
    ['Jindrichuv Hradec', 'Trebon'],
    ['Trebon', 'Ceske Budejovice'],
  ],
  'race-spain': [
    ['Monaco', 'Monaco'],
    ['Monaco', 'Manosque'],
    ['Gruissan', 'Font Romeu'],
    ['Andorra la Vella', 'Andorra la Vella'],
    ['Falset', 'Roquetes'],
    ['Alcossebre', 'Castello'],
    ["Vall d'Alba", 'Valdelinares'],
    ['Pucol', 'Xeraco'],
    ['Villajoyosa', 'Alto de Aitana'],
    ['Alcaraz', 'Elche de la Sierra'],
    ['Cartagena', 'Lorca'],
    ['Vera', 'Calar Alto'],
    ['Almunecar', 'Loja'],
    ['Jaen', 'Sierra de la Pandera'],
    ['Palma del Rio', 'Cordoba'],
    ['Cortegana', 'La Rabida'],
    ['Dos Hermanas', 'Sevilla'],
    ['El Puerto de Santa Maria', 'Jerez de la Frontera'],
    ['Velez-Malaga', 'Penas Blancas'],
    ['La Calahorra', 'Collada de Alguacil'],
    ['Granada', 'Granada'],
  ],
  'race-sundvolden': [['Sundvollen', 'Norefjell']],
  'race-surf-coast': [['Geelong', 'Geelong']],
  'race-switzerland': [
    ['Sondrio', 'Sondrio'],
    ['Locarno', 'Locarno'],
    ['Bad Ragaz', 'Bad Ragaz'],
    ['Aarburg', 'Aarburg'],
    ['Villars-sur-Ollon', 'Villars-sur-Ollon'],
  ],
  'race-syedra': [['Alanya', 'Gazipasa']],
  'race-szekler': [
    ['Sfantu Gheorghe', 'Miercurea Ciuc'],
    ['Miercurea Ciuc', 'Gheorgheni'],
    ['Gheorgheni', 'Odorheiu Secuiesc'],
  ],
  'race-tachira': [
    ['San Cristobal', 'La Fria'],
    ['La Fria', 'Michelena'],
    ['Michelena', 'Colon'],
    ['Colon', 'La Grita'],
    ['La Grita', 'Seboruco'],
    ['Seboruco', 'Queniquea'],
    ['Queniquea', 'Tariba'],
    ['Tariba', 'Palmira'],
    ['Palmira', 'San Cristobal'],
  ],
  'race-taihu': [
    ['Wuxi', 'Suzhou'],
    ['Suzhou', 'Wujiang'],
    ['Wujiang', 'Huzhou'],
    ['Huzhou', 'Yixing'],
    ['Yixing', 'Wuxi'],
  ],
  'race-taiwan': [
    ['Taipei', 'Taoyuan'],
    ['Taoyuan', 'Miaoli'],
    ['Miaoli', 'Taichung'],
    ['Taichung', 'Puli'],
    ['Puli', 'Nantou'],
  ],
  'race-thailand': [
    ['Chiang Mai', 'Lamphun'],
    ['Lamphun', 'Lampang'],
    ['Lampang', 'Phrae'],
    ['Phrae', 'Nan'],
    ['Nan', 'Phayao'],
    ['Phayao', 'Chiang Rai'],
  ],
  'race-to-the-sun': [
    ['Acheres', 'Carrieres-sous-Poissy'],
    ['Epone', 'Montargis'],
    ['Cosne-Cours-sur-Loire', 'Pouilly-sur-Loire'],
    ['Bourges', 'Uchon'],
    ['Cormoranche-sur-Saone', 'Colombier-le-Vieux'],
    ['Barbentane', 'Apt'],
    ['Nice', 'Isola-Village'],
    ['Nice', 'Nice'],
  ],
  'race-torres-vedras': [
    ['Torres Vedras', 'Lourinha'],
    ['Lourinha', 'Mafra'],
    ['Mafra', 'Torres Vedras'],
  ],
  'race-toscana': [['Arezzo', 'Siena']],
  'race-tourangelle': [['Azay-le-Rideau', 'Tours']],
  'race-tours': [['Chartres', 'Tours']],
  'race-tramuntana': [['Soller', 'Sa Calobra']],
  'race-troyes': [['Troyes', 'Troyes']],
  'race-turin': [['Milano', 'Torino']],
  'race-turkiye': [
    ['Antalya', 'Kemer'],
    ['Kemer', 'Elmali'],
    ['Elmali', 'Fethiye'],
    ['Fethiye', 'Marmaris'],
    ['Marmaris', 'Bodrum'],
    ['Bodrum', 'Selcuk'],
    ['Selcuk', 'Kusadasi'],
    ['Kusadasi', 'Izmir'],
  ],
  'race-two-seas': [
    ['Lido di Camaiore', 'Lido di Camaiore'],
    ['Camaiore', 'San Gimignano'],
    ['Cortona', 'Magliano dei Marsi'],
    ['Tagliacozzo', 'Martinsicuro'],
    ['Marotta-Mondolfo', 'Mombaroccio'],
    ['San Severino Marche', 'Camerino'],
    ['Civitanova Marche', 'San Benedetto del Tronto'],
  ],
  'race-umag': [['Novigrad', 'Umag']],
  'race-valencia': [
    ['Valencia', 'Gandia'],
    ['Gandia', 'Alcoy'],
    ['Alcoy', 'Xativa'],
    ['Xativa', 'Sagunto'],
    ['Sagunto', 'Valencia'],
  ],
  'race-valencia-gp': [['Valencia', 'Valencia']],
  'race-var': [['Draguignan', 'Draguignan']],
  'race-varese': [['Varese', 'Varese']],
  'race-veenendaal': [['Veenendaal', 'Veenendaal']],
  'race-vendee': [['La Roche-sur-Yon', 'La Roche-sur-Yon']],
  'race-vendemiano': [['Conegliano', 'San Vendemiano']],
  'race-veneto': [['Padova', 'Vicenza']],
  'race-veneto-classic': [['Venezia', 'Bassano del Grappa']],
  'race-venezuela': [
    ['San Cristobal', 'La Fria'],
    ['La Fria', 'La Grita'],
    ['La Grita', 'Bailadores'],
    ['Bailadores', 'Merida'],
    ['Merida', 'Timotes'],
    ['Timotes', 'La Puerta'],
    ['La Puerta', 'Valera'],
    ['Valera', 'Bocono'],
  ],
  'race-victoria': [
    ['Melbourne', 'Sorrento'],
    ['Sorrento', 'Arthurs Seat'],
    ['Arthurs Seat', 'Melbourne'],
    ['Melbourne', 'Kinglake'],
    ['Kinglake', 'Healesville'],
  ],
  'race-visegrad-cz': [['Brno', 'Blansko']],
  'race-vitre': [['Vitre', 'Vitre']],
  'race-vlaanderen': [['Brugge', 'Gent']],
  'race-vorarlberg': [['Bregenz', 'Bludenz']],
  'race-waasland': [['Sint-Niklaas', 'Lokeren']],
  'race-wallonia': [
    ['Mons', 'Charleroi'],
    ['Charleroi', 'Namur'],
    ['Namur', 'Andenne'],
    ['Andenne', 'Huy'],
    ['Huy', 'Liege'],
  ],
  'race-wallonie-circuit': [['Charleroi', 'Namur']],
  'race-walloon-wall': [['Namur', 'Huy']],
  'race-west-bohemia': [
    ['Plzen', 'Karlovy Vary'],
    ['Karlovy Vary', 'Marianske Lazne'],
    ['Marianske Lazne', 'Cheb'],
    ['Cheb', 'Plzen'],
  ],
  'race-wevelgem': [['Ieper', 'Wevelgem']],
  'race-white-roads': [['Siena', 'Siena']],
  'race-woensdrecht': [['Bergen op Zoom', 'Woensdrecht']],
  'race-youngster': [['Nieuwpoort', 'Koksijde']],
  'race-zaglebie': [['Sosnowiec', 'Dabrowa Gornicza']],
  'race-zlm': [
    ['Eindhoven', 'Weert'],
    ['Weert', 'Sittard'],
    ['Sittard', 'Roermond'],
    ['Roermond', 'Valkenburg'],
    ['Valkenburg', 'Maastricht'],
  ],
  'race-zwolle': [['Zwolle', 'Zwolle']],
}

/** Recorrido de una carrera como pares [salida, meta] por etapa, o null si no está definido. */
export function raceRoute(raceId: string): [string, string][] | null {
  return RACE_ROUTES[raceId] ?? null
}

/** De dónde a dónde va una etapa concreta (1-based), o null si no hay recorrido/índice fuera de rango. */
export function stageEndpoints(
  raceId: string,
  stageIndex: number,
): { from: string; to: string } | null {
  const route = RACE_ROUTES[raceId]
  if (!route || stageIndex < 1 || stageIndex > route.length) return null
  const pair = route[stageIndex - 1]!
  return { from: pair[0], to: pair[1] }
}
