/**
 * Recorridos reales por carrera: la secuencia de localidades (reales) que recorre cada prueba,
 * anclada a su ubicación de verdad (la carrera lleva el nombre de su sitio) y a su terreno. La etapa
 * i (1-based) va de route[i-1] a route[i]; una prueba de N etapas tiene N+1 localidades encadenadas
 * (el final de una etapa es la salida de la siguiente), como una carrera real. Las de un día suelen
 * ser un circuito (salida = meta en su localidad). Datos de autoría; nombres ASCII sin tildes.
 *
 * Invariante (verificado en test): RACE_ROUTES[id].length === (nº de etapas de la carrera) + 1.
 */
export const RACE_ROUTES: Record<string, string[]> = {
  'race-abruzzo': ['Pescara', 'Vasto', 'Roccaraso', 'Sulmona', 'Blockhaus'],
  'race-achterhoek': ['Doetinchem', 'Winterswijk'],
  'race-across-flanders': ['Roeselare', 'Waregem'],
  'race-aegean': ['Izmir', 'Selcuk'],
  'race-agostoni': ['Lissone', 'Lissone'],
  'race-ain': ['Bourg-en-Bresse', 'Oyonnax', 'Lelex', 'Grand Colombier'],
  'race-alaiye': ['Alanya', 'Manavgat'],
  'race-alanya': ['Alanya', 'Side'],
  'race-albania': ['Tirana', 'Durres', 'Kavaje', 'Fier', 'Vlore', 'Berat'],
  'race-alentejo': ['Grandola', 'Beja', 'Evora', 'Estremoz', 'Portalegre', 'Elvas'],
  'race-algarve': ['Lagos', 'Portimao', 'Alto da Foia', 'Tavira', 'Alto do Malhao', 'Alto da Foia'],
  'race-algeria': ['Algiers', 'Blida', 'Medea', 'Bouira', 'Setif', 'Setif', 'Constantine'],
  'race-almeria': ['Almeria', 'Roquetas de Mar'],
  'race-alpes-maritimes': ['Nice', 'Nice'],
  'race-alps': [
    'Trento',
    'Bolzano',
    'Passo Pordoi',
    'Cavalese',
    'Alpe di Pampeago',
    'Plan de Corones',
  ],
  'race-alsace': [
    'Strasbourg',
    'Colmar',
    'Le Markstein',
    'Mulhouse',
    "Ballon d'Alsace",
    'Grand Ballon',
  ],
  'race-amstel': ['Maastricht', 'Valkenburg'],
  'race-andalusia': [
    'Cordoba',
    'Baena',
    'Alto de Hazallanas',
    'Granada',
    'Sierra Nevada',
    'Alto de Velefique',
  ],
  'race-andorra-classic': ['Andorra la Vella', 'Arcalis'],
  'race-andratx': ['Andratx', 'Palma'],
  'race-anicolor': ['Aveiro', 'Porto', 'Guimaraes', 'Braga'],
  'race-annemasse': ['Annemasse', 'Annemasse'],
  'race-antalya': ['Antalya', 'Kemer', 'Elmali', 'Korkuteli', 'Serik'],
  'race-antalya-gp': ['Antalya', 'Side'],
  'race-antwerp': ['Antwerpen', 'Antwerpen'],
  'race-apollon': ['Limassol', 'Larnaca'],
  'race-appennino': ['Novi Ligure', 'Genova'],
  'race-aquitaine': ['Bordeaux', 'Libourne', 'Bergerac', 'Perigueux', 'Agen'],
  'race-arabia': ['Riyadh', 'Diriyah', 'Thumamah', 'Al Majmaah', 'Shaqra', 'Dawadmi'],
  'race-arctic': ['Bodo', 'Fauske', 'Narvik', 'Harstad', 'Tromso'],
  'race-ardeche': ['Guilherand-Granges', 'Aubenas'],
  'race-ardennes': ['Liege', 'Huy', 'Aywaille', 'Stavelot', 'Spa', 'Liege'],
  'race-arrabida': ['Setubal', 'Sesimbra'],
  'race-artois': ['Arras', 'Arras'],
  'race-arvedi': ['Cremona', 'Cremona'],
  'race-asturias': ['Oviedo', 'Gijon', 'Lagos de Covadonga', 'Alto del Angliru'],
  'race-aulne': ['Chateaulin', 'Chateaulin'],
  'race-austria': [
    'Salzburg',
    'Zell am See',
    'Heiligenblut',
    'Sankt Johann im Pongau',
    'Bad Gastein',
    'Kitzbuhel',
  ],
  'race-aveiro': ['Aveiro', 'Ovar'],
  'race-baku': ['Baku', 'Sumqayit', 'Shamakhi', 'Kurdamir', 'Gabala', 'Ganja'],
  'race-baltic': ['Klaipeda', 'Palanga', 'Telsiai', 'Kretinga'],
  'race-basque-country': [
    'Vitoria',
    'Amurrio',
    'Arrate',
    'Tolosa',
    'Jaizkibel',
    'Hondarribia',
    'Arrate',
  ],
  'race-beauce': [
    'Sainte-Marie',
    'Saint-Georges',
    'Lac-Megantic',
    'Beauceville',
    'Saint-Joseph-de-Beauce',
    'Saint-Georges',
  ],
  'race-belgium': ['Antwerpen', 'Gent', 'Geraardsbergen', 'Leuven', 'Huy', 'Namur'],
  'race-belgrade': ['Belgrade', 'Smederevo', 'Pancevo', 'Novi Sad', 'Sremski Karlovci'],
  'race-belvedere': ['Villa Lagarina', 'Villa Lagarina'],
  'race-benelux': ['Brugge', 'Antwerpen', 'Geraardsbergen', 'Aalst', 'Oudenaarde', 'Gent'],
  'race-benin': ['Cotonou', 'Porto-Novo', 'Dassa-Zoume', 'Parakou', 'Natitingou', 'Djougou'],
  'race-besancon': ['Besancon', 'Besancon'],
  'race-beskid': ['Bielsko-Biala', 'Szczyrk'],
  'race-beskid-race': ['Zywiec', 'Wisla'],
  'race-besseges': ['Bellegarde', 'Nimes', 'Besseges', 'Ales', 'Laudun', 'La Grande-Motte'],
  'race-biella': ['Biella', 'Biella'],
  'race-binche': ['Binche', 'Binche'],
  'race-bosnia': ['Mostar', 'Sarajevo', 'Jahorina', 'Bjelasnica'],
  'race-braakman': ['Terneuzen', 'Terneuzen'],
  'race-brabant': ['Leuven', 'Overijse'],
  'race-brda': ['Nova Gorica', 'Dobrovo'],
  'race-bredene': ['Bredene', 'Koksijde'],
  'race-bretagne': [
    'Saint-Brieuc',
    'Loudeac',
    'Carhaix',
    'Quimper',
    'Lorient',
    'Pontivy',
    'Pontivy',
    'Vannes',
  ],
  'race-britain': [
    'Sheffield',
    'Barnsley',
    'Holmfirth',
    'Huddersfield',
    'Hebden Bridge',
    'Halifax',
  ],
  'race-brittany': ['Rennes', 'Rennes'],
  'race-bruges': ['Brugge', 'De Panne'],
  'race-brussels': ['Brussel', 'Brussel'],
  'race-bulgaria': ['Sofia', 'Plovdiv', 'Karlovo', 'Kazanlak', 'Sliven', 'Yambol', 'Burgas'],
  'race-burgos': [
    'Burgos',
    'Lerma',
    'Lagunas de Neila',
    'Salas de los Infantes',
    'Picon Blanco',
    'Burgos',
  ],
  'race-calvia': ['Calvia', 'Palma'],
  'race-camembert': ['Camembert', 'Vimoutiers'],
  'race-cameroon': [
    'Yaounde',
    'Douala',
    'Bafoussam',
    'Foumban',
    'Dschang',
    'Bafang',
    'Bamenda',
    'Bamenda',
    'Bafoussam',
  ],
  'race-castellon': ['Castellon', 'Valencia'],
  'race-castilla-leon': ['Valladolid', 'Segovia'],
  'race-catalonia': [
    'Calella',
    'Sant Feliu de Guixols',
    'Vallter 2000',
    'Olot',
    'La Molina',
    'Berga',
    'Vic',
    'Barcelona',
  ],
  'race-cerami': ['Quaregnon', 'Frameries'],
  'race-chauny': ['Chauny', 'Chauny'],
  'race-cholet': ['Cholet', 'Cholet'],
  'race-chrono': ['Les Herbiers', 'Les Herbiers'],
  'race-colombia': [
    'Medellin',
    'Rionegro',
    'La Union',
    'El Carmen de Viboral',
    'El Retiro',
    'Rionegro',
    'Medellin',
  ],
  'race-colombia-tour': [
    'Medellin',
    'Rionegro',
    'La Union',
    'Sonson',
    'Abejorral',
    'Santa Barbara',
    'Alto de Minas',
    'Amaga',
    'Caldas',
    'Medellin',
  ],
  'race-communes': ['Mons', 'La Louviere'],
  'race-copenhagen': ['Copenhagen', 'Copenhagen'],
  'race-criquielion': ['Lessines', 'Lessines'],
  'race-croatia': ['Rijeka', 'Crikvenica', 'Ucka', 'Opatija', 'Platak', 'Delnice', 'Sljeme'],
  'race-czechia': ['Brno', 'Vyskov', 'Blansko', 'Boskovice', 'Brno'],
  'race-denain': ['Denain', 'Denain'],
  'race-denmark': ['Copenhagen', 'Nyborg', 'Vejle', 'Kolding', 'Silkeborg', 'Aarhus'],
  'race-dodecanese': ['Lindos', 'Rhodes'],
  'race-doubs': ['Pontarlier', 'Pontarlier'],
  'race-down-under': [
    'Tanunda',
    'Lyndoch',
    'Lobethal',
    'Adelaide',
    'Stirling',
    'Aldgate',
    'Willunga',
  ],
  'race-drome': ['Valence', 'Valence'],
  'race-dunkerque': ['Dunkerque', 'Dunkerque'],
  'race-ebre': ['Tortosa', 'Gandesa'],
  'race-ecuador': ['Quito', 'Latacunga', 'Zumbahua', 'Ambato', 'Riobamba', 'Guano', 'Banos'],
  'race-elfsteden': ['Bolsward', 'Bolsward'],
  'race-emilia': ['Carpi', 'Bologna'],
  'race-emilia-gp': ['Reggio Emilia', 'Modena'],
  'race-emirates': [
    'Abu Dhabi',
    'Al Ain',
    'Jebel Hafeet',
    'Dubai',
    'Hatta',
    'Sharjah',
    'Jebel Jais',
    'Ras Al Khaimah',
  ],
  'race-estonia': ['Tallinn', 'Parnu', 'Viljandi', 'Tartu'],
  'race-estrela': ['Guarda', 'Covilha', 'Torre', 'Penhas da Saude'],
  'race-euro-champs': ['Plumelec', 'Plumelec'],
  'race-fagnes': ['Eupen', 'Malmedy'],
  'race-famenne': ['Marche-en-Famenne', 'Marche-en-Famenne'],
  'race-faso': [
    'Ouagadougou',
    'Koudougou',
    'Bobo-Dioulasso',
    'Banfora',
    'Sindou',
    'Bobo-Dioulasso',
  ],
  'race-figueira': ['Figueira da Foz', 'Montemor-o-Velho'],
  'race-finistere': ['Quimper', 'Quimper'],
  'race-flanders': ['Antwerpen', 'Oudenaarde'],
  'race-flandrien': ['Zottegem', 'Oudenaarde'],
  'race-fleche-ardennaise': ['Malmedy', 'Aywaille'],
  'race-fleche-sud': [
    'Esch-sur-Alzette',
    'Dudelange',
    'Rumelange',
    'Differdange',
    'Petange',
    'Esch-sur-Alzette',
  ],
  'race-fourmies': ['Fourmies', 'Fourmies'],
  'race-france': [
    'Brest',
    'Quimper',
    'Pontivy',
    'Nantes',
    'La Roche-sur-Yon',
    'La Roche-sur-Yon',
    'La Rochelle',
    'Bordeaux',
    'Pau',
    'Luz Ardiden',
    'Bagneres-de-Luchon',
    'Plateau de Beille',
    'Foix',
    'Carcassonne',
    'Mont Aigoual',
    'Nimes',
    'Mont Ventoux',
    'Orcieres-Merlette',
    'Briancon',
    'Briancon',
    "Alpe d'Huez",
    'Paris',
  ],
  'race-franco-belgian': ['Lille', 'Roubaix'],
  'race-frankfurt': ['Eschborn', 'Frankfurt'],
  'race-friuli': ['Pordenone', 'Udine', 'Cividale del Friuli', 'Gorizia', 'Trieste'],
  'race-funen': ['Odense', 'Odense'],
  'race-galicia': ['A Coruna', 'Santiago de Compostela', 'Ezaro', 'Pontevedra', 'Manzaneda'],
  'race-germany': ['Stuttgart', 'Karlsruhe', 'Baden-Baden', 'Offenburg', 'Freiburg', 'Lorrach'],
  'race-getxo': ['Getxo', 'Getxo'],
  'race-gila': ['Silver City', 'Hurley', 'Mogollon', 'Pinos Altos', 'Lake Roberts', 'Silver City'],
  'race-gippingen': ['Baden', 'Bad Zurzach'],
  'race-gooik': ['Gooik', 'Gooik'],
  'race-great-ocean': ['Torquay', 'Torquay'],
  'race-guangxi': ['Beihai', 'Nanning', 'Nongla', 'Liuzhou', 'Lipu', 'Yangshuo', 'Guilin'],
  'race-guatemala': [
    'Guatemala City',
    'Escuintla',
    'Antigua',
    'Chimaltenango',
    'Tecpan',
    'Quetzaltenango',
  ],
  'race-hainan': ['Haikou', 'Wenchang', 'Qionghai', 'Wanning', 'Wuzhishan', 'Sanya'],
  'race-halle': ['Halle', 'Ingooigem'],
  'race-hamburg': ['Buxtehude', 'Hamburg'],
  'race-harelbeke': ['Harelbeke', 'Harelbeke'],
  'race-hauts-de-france': ['Amiens', 'Arras', 'Lille', 'Valenciennes', 'Cambrai', 'Saint-Quentin'],
  'race-heist': ['Heist-op-den-Berg', 'Heist-op-den-Berg'],
  'race-hellas': ['Athens', 'Thebes', 'Livadia', 'Delphi', 'Arachova', 'Lamia'],
  'race-herning': ['Herning', 'Herning'],
  'race-holland': [
    'Amsterdam',
    'Utrecht',
    'Arnhem',
    'Venlo',
    'Valkenburg',
    'Sittard',
    'Maastricht',
  ],
  'race-houtland': ['Torhout', 'Lichtervelde'],
  'race-hungary': ['Budapest', 'Szekesfehervar', 'Veszprem', 'Kaposvar', 'Pecs', 'Szekszard'],
  'race-huy': ['Charleroi', 'Huy'],
  'race-isbergues': ['Isbergues', 'Isbergues'],
  'race-isere': [
    'Vienne',
    'Grenoble',
    'Chamrousse',
    'Villard-de-Lans',
    "Alpe d'Huez",
    'Les Deux Alpes',
  ],
  'race-istanbul': ['Istanbul', 'Gebze', 'Kartepe', 'Sapanca', 'Adapazari'],
  'race-istria': ['Pula', 'Rovinj', 'Porec', 'Umag', 'Pazin'],
  'race-italy': [
    'Napoli',
    'Salerno',
    'Foggia',
    'Campobasso',
    'Pescara',
    'Blockhaus',
    'Teramo',
    'Ascoli Piceno',
    'Fermo',
    'Recanati',
    'Monte Carpegna',
    'Cesena',
    'Bologna',
    'Corno alle Scale',
    'Modena',
    'Verona',
    'Monte Bondone',
    'Passo del Tonale',
    'Clusone',
    'Bergamo',
    'Passo della Presolana',
    'Milano',
  ],
  'race-jaen': ['Ubeda', 'Jaen'],
  'race-japan': ['Kyoto', 'Kyoto'],
  'race-jura': ['Lons-le-Saunier', 'Les Rousses'],
  'race-kempen': ['Herentals', 'Turnhout'],
  'race-koln': ['Koln', 'Bonn'],
  'race-korea': ['Seoul', 'Chungju', 'Mungyeong', 'Andong', 'Yeongju', 'Danyang'],
  'race-kosovo': ['Pristina', 'Ferizaj', 'Prizren', 'Gjakova', 'Peja'],
  'race-kranj': ['Kranj', 'Trzic'],
  'race-kreiz-breizh': ['Rostrenen', 'Carhaix', 'Mur-de-Bretagne', 'Gouarec', 'Callac'],
  'race-kumano': ['Kumano', 'Nachikatsuura', 'Hongu', 'Shingu', 'Kumano'],
  'race-kuurne': ['Kuurne', 'Kuurne'],
  'race-kyushu': ['Fukuoka', 'Hita', 'Kokonoe', 'Beppu'],
  'race-laigueglia': ['Laigueglia', 'Laigueglia'],
  'race-langkawi': [
    'Langkawi',
    'Kangar',
    'Sungai Petani',
    'Ipoh',
    'Cameron Highlands',
    'Kuala Kubu Bharu',
    'Genting Highlands',
    'Kuala Lumpur',
    'Melaka',
  ],
  'race-lazio': ['Frosinone', 'Roma'],
  'race-legnano': ['Legnano', 'Legnano'],
  'race-leon': ['Leon', 'Leon'],
  'race-liberazione': ['Roma', 'Roma'],
  'race-liege': ['Liege', 'Liege'],
  'race-liege-espoirs': ['Bastogne', 'Liege'],
  'race-lillers': ['Lillers', 'Lillers'],
  'race-limburg': ['Maastricht', 'Valkenburg'],
  'race-limousin': ['Limoges', 'Saint-Yrieix-la-Perche', 'Brive-la-Gaillarde', 'Tulle', 'Gueret'],
  'race-lithuania': ['Vilnius', 'Trakai', 'Alytus', 'Druskininkai', 'Kaunas', 'Kedainiai'],
  'race-loir-cher': [
    'Blois',
    'Vendome',
    'Montoire-sur-le-Loir',
    'Romorantin-Lanthenay',
    'Salbris',
    'Blois',
  ],
  'race-loire': ['Roanne', 'Feurs', 'Saint-Etienne', 'Montbrison', 'Charlieu'],
  'race-loire-atlantique': ['Nantes', 'Saint-Nazaire'],
  'race-lombardy': ['Bergamo', 'Como'],
  'race-luxembourg': [
    'Esch-sur-Alzette',
    'Dudelange',
    'Diekirch',
    'Echternach',
    'Wiltz',
    'Luxembourg',
  ],
  'race-lyon': ['Lyon', 'Villefranche-sur-Saone', 'Chiroubles', 'Yzeron'],
  'race-magna-grecia': ['Sibari', 'Crotone', 'Camigliatello Silano', 'Gambarie'],
  'race-malopolska': ['Krakow', 'Tarnow', 'Nowy Sacz', 'Krakow'],
  'race-maras': ['Kahramanmaras', 'Gaziantep', 'Islahiye', 'Osmaniye', 'Adana'],
  'race-marseille': ['Marseille', 'Marseille'],
  'race-maryland': ['Baltimore', 'Frederick', 'Cumberland', 'Hagerstown'],
  'race-matteotti': ['Pescara', 'Pescara'],
  'race-mauritius': ['Port Louis', 'Grand Baie', 'Curepipe', 'Mahebourg', 'Port Louis'],
  'race-mayenne': ['Laval', 'Mayenne', 'Ernee', 'Chateau-Gontier', 'Laval'],
  'race-mazury': ['Olsztyn', 'Mragowo', 'Gizycko', 'Elk'],
  'race-mercantour': ['Nice', 'Isola 2000'],
  'race-mersin': ['Mersin', 'Erdemli', 'Silifke', 'Tarsus', 'Adana'],
  'race-mirabelle': ['Nancy', 'Nancy'],
  'race-monsere': ['Roeselare', 'Hooglede'],
  'race-montreal': ['Montreal', 'Montreal'],
  'race-morbihan': ['Grand-Champ', 'Grand-Champ'],
  'race-morocco': [
    'Casablanca',
    'Marrakesh',
    'Asni',
    'Amizmiz',
    'Setti Fatma',
    'Tahannaout',
    'Oukaimeden',
    'Oukaimeden',
    'Asni',
  ],
  'race-morvedre': ['Sagunto', 'Segorbe'],
  'race-munster': ['Munster', 'Telgte'],
  'race-murcia': ['Murcia', 'Cartagena', 'Alhama de Murcia'],
  'race-muscat': ['Muscat', 'Barka'],
  'race-muur': ['Ninove', 'Geraardsbergen'],
  'race-namur': ['Namur', 'Namur'],
  'race-navarre': ['Estella', 'Pamplona'],
  'race-nippon': [
    'Shizuoka',
    'Numazu',
    'Izu',
    'Ito',
    'Hakone',
    'Gotemba',
    'Fujiyoshida',
    'Yamanakako',
    'Fujinomiya',
  ],
  'race-nokere': ['Deinze', 'Nokere'],
  'race-norway': ['Oslo', 'Drammen', 'Norefjell', 'Honefoss', 'Oslo'],
  'race-novo-mesto': ['Novo Mesto', 'Otocec'],
  'race-nxt': ['Emmen', 'Hoogeveen'],
  'race-oberosterreich': ['Linz', 'Wels', 'Steyr', 'Enns', 'Linz'],
  'race-occitanie': ['Auch', 'Toulouse', 'Luz Ardiden', 'Tarbes', 'Peyragudes'],
  'race-oise': ['Beauvais', 'Clermont', 'Senlis', 'Compiegne', 'Noyon'],
  'race-olympia': ['Apeldoorn', 'Nijmegen', 'Arnhem', 'Venlo', 'Valkenburg', 'Maastricht'],
  'race-oman': ['Muscat', 'Nizwa', 'Jabal Al Akhdar', 'Al Hamra', 'Jabal Shams', 'Al Amerat'],
  'race-ontur': ['Ontur', 'Hellin'],
  'race-opening-classic': ['Gent', 'Ninove'],
  'race-ordizia': ['Ordizia', 'Ordizia'],
  'race-oropa': ['Biella', 'Oropa'],
  'race-overijssel': ['Rijssen', 'Rijssen'],
  'race-palma': ['Palma', 'Palma'],
  'race-pantani': ['Cesenatico', 'Monte Carpegna'],
  'race-pascua': ['Estella', 'Estella'],
  'race-peccioli': ['Peccioli', 'Peccioli'],
  'race-pedalia': ['Marathon', 'Athens'],
  'race-philadelphia': ['Philadelphia', 'Philadelphia'],
  'race-piedmont': ['Omegna', 'Torino'],
  'race-piva': ['Farra di Soligo', 'Farra di Soligo'],
  'race-plouay': ['Plouay', 'Plouay'],
  'race-poland': [
    'Katowice',
    'Krakow',
    'Nowy Sacz',
    'Tarnow',
    'Krynica-Zdroj',
    'Nowy Targ',
    'Zakopane',
    'Bukowina Tatrzanska',
  ],
  'race-polynormande': ['Saint-Martin-de-Landelles', 'Saint-Martin-de-Landelles'],
  'race-popolarissima': ['Treviso', 'Treviso'],
  'race-porec': ['Motovun', 'Porec'],
  'race-portugal': [
    'Faro',
    'Beja',
    'Marvao',
    'Castelo Branco',
    'Torre',
    'Viseu',
    'Montemuro',
    'Porto',
    'Senhora da Graca',
    'Guimaraes',
    'Larouco',
  ],
  'race-poyang': ['Nanchang', 'Jiujiang', 'Lushan', 'Jingdezhen', 'Wuyuan', 'Shangrao', 'Poyang'],
  'race-prato': ['Prato', 'Prato'],
  'race-provence': ['Marseille', 'Salon-de-Provence', 'Montagne de Lure', 'Chalet Reynard'],
  'race-pune': ['Pune', 'Lonavala', 'Lavasa', 'Panchgani', 'Mahabaleshwar', 'Sinhagad'],
  'race-qinghai': [
    'Xining',
    'Huangyuan',
    'Gonghe',
    'Chaka',
    'Heimahe',
    'Gangcha',
    'Haiyan',
    'Xihai',
    'Menyuan',
  ],
  'race-quebec': ['Quebec City', 'Quebec City'],
  'race-recioto': ['Negrar', 'Negrar'],
  'race-reggio': ['Reggio Emilia', 'Reggio Emilia'],
  'race-rhodes': ['Rhodes', 'Faliraki', 'Archangelos', 'Lindos', 'Ialysos'],
  'race-rhodes-gp': ['Rhodes', 'Lindos'],
  'race-rhone-alpes': [
    'Vichy',
    'Clermont-Ferrand',
    'Le Mont-Dore',
    'Saint-Etienne',
    'Chamrousse',
    'Grenoble',
    "Alpe d'Huez",
    "Alpe d'Huez",
    'La Toussuire',
  ],
  'race-ringerike': ['Honefoss', 'Honefoss'],
  'race-romagna': ['Rimini', 'Cesenatico', 'Cesena', 'Forli', 'Faenza', 'Imola'],
  'race-romagna-giro': ['Lugo', 'Faenza'],
  'race-romandy': ['Geneva', 'Fribourg', 'Leysin', 'Sion', 'Verbier', 'Sion', 'Villars'],
  'race-romania': ['Cluj-Napoca', 'Targu Mures', 'Sighisoara', 'Medias', 'Sibiu', 'Alba Iulia'],
  'race-roubaix': ['Compiegne', 'Roubaix'],
  'race-roubaix-espoirs': ['Bohain-en-Vermandois', 'Roubaix'],
  'race-rucphen': ['Roosendaal', 'Rucphen'],
  'race-rutland': ['Oakham', 'Oakham'],
  'race-rwanda': [
    'Kigali',
    'Huye',
    'Rusizi',
    'Karongi',
    'Rubavu',
    'Musanze',
    'Muhanga',
    'Kigali',
    'Kigali',
  ],
  'race-samsun': ['Samsun', 'Carsamba', 'Unye', 'Fatsa', 'Ordu'],
  'race-samyn': ['Quaregnon', 'Dour'],
  'race-san-daniele': ['San Daniele del Friuli', 'San Daniele del Friuli'],
  'race-san-sebastian': ['San Sebastian', 'San Sebastian'],
  'race-sanremo': ['Milano', 'Sanremo'],
  'race-sardegna': ['Cagliari', 'Sassari', 'Alghero', 'Olbia', 'Nuoro', 'Cagliari'],
  'race-sauerland': ['Arnsberg', 'Meschede', 'Winterberg', 'Brilon', 'Arnsberg'],
  'race-schelde': ['Antwerpen', 'Schoten'],
  'race-serbie': ['Belgrade', 'Kragujevac', 'Kraljevo', 'Cacak', 'Uzice'],
  'race-ses-salines': ['Ses Salines', 'Sa Calobra'],
  'race-sharjah': ['Sharjah', 'Ajman', 'Ras Al Khaimah', 'Dibba', 'Khor Fakkan', 'Fujairah'],
  'race-sibiu': ['Sibiu', 'Medias', 'Paltinis', 'Fagaras', 'Balea Lac'],
  'race-slezanski': ['Wroclaw', 'Sobotka'],
  'race-slovakia': ['Bratislava', 'Trnava', 'Nitra', 'Banska Bystrica', 'Poprad', 'Kosice'],
  'race-slovenia': ['Ljubljana', 'Maribor', 'Rogla', 'Celje', 'Velika Planina', 'Kranjska Gora'],
  'race-slovenian-istria': ['Koper', 'Piran'],
  'race-solidarnosc': ['Lodz', 'Piotrkow Trybunalski', 'Czestochowa', 'Radomsko', 'Lodz'],
  'race-somme': ['Amiens', 'Amiens'],
  'race-south-bohemia': [
    'Ceske Budejovice',
    'Tabor',
    'Jindrichuv Hradec',
    'Trebon',
    'Ceske Budejovice',
  ],
  'race-spain': [
    'Sevilla',
    'Cordoba',
    'Baena',
    'Jaen',
    'Guadix',
    'Sierra Nevada',
    'Almeria',
    'Lorca',
    'Elche',
    'Alicante',
    'Alto de Aitana',
    'Valencia',
    'Castellon',
    'Penyagolosa',
    'Tortosa',
    'Tarragona',
    'Montserrat',
    'La Molina',
    'Vic',
    'Girona',
    'Rocacorba',
    'Barcelona',
  ],
  'race-sundvolden': ['Sundvollen', 'Norefjell'],
  'race-surf-coast': ['Geelong', 'Geelong'],
  'race-switzerland': [
    'Zurich',
    'Frauenfeld',
    'Andermatt',
    'Airolo',
    'San Bernardino',
    'Chur',
    'St. Moritz',
    'Pontresina',
    'Andermatt',
  ],
  'race-syedra': ['Alanya', 'Gazipasa'],
  'race-szekler': ['Sfantu Gheorghe', 'Miercurea Ciuc', 'Gheorgheni', 'Odorheiu Secuiesc'],
  'race-tachira': [
    'San Cristobal',
    'La Fria',
    'Michelena',
    'Colon',
    'La Grita',
    'Seboruco',
    'Queniquea',
    'Tariba',
    'Palmira',
    'San Cristobal',
  ],
  'race-taihu': ['Wuxi', 'Suzhou', 'Wujiang', 'Huzhou', 'Yixing', 'Wuxi'],
  'race-taiwan': ['Taipei', 'Taoyuan', 'Miaoli', 'Taichung', 'Puli', 'Nantou'],
  'race-thailand': ['Chiang Mai', 'Lamphun', 'Lampang', 'Phrae', 'Nan', 'Phayao', 'Chiang Rai'],
  'race-to-the-sun': [
    'Le Perray-en-Yvelines',
    'Montargis',
    'La Loge des Gardes',
    'Valence',
    'Chalet Reynard',
    'Sisteron',
    'La Turbie',
    'La Turbie',
    'Col de Turini',
  ],
  'race-torres-vedras': ['Torres Vedras', 'Lourinha', 'Mafra', 'Torres Vedras'],
  'race-toscana': ['Arezzo', 'Siena'],
  'race-tourangelle': ['Azay-le-Rideau', 'Tours'],
  'race-tours': ['Chartres', 'Tours'],
  'race-tramuntana': ['Soller', 'Sa Calobra'],
  'race-troyes': ['Troyes', 'Troyes'],
  'race-turin': ['Milano', 'Torino'],
  'race-turkiye': [
    'Antalya',
    'Kemer',
    'Elmali',
    'Fethiye',
    'Marmaris',
    'Bodrum',
    'Selcuk',
    'Kusadasi',
    'Izmir',
  ],
  'race-two-seas': [
    'Lido di Camaiore',
    'Camaiore',
    'Follonica',
    'Foligno',
    'Sarnano',
    'Recanati',
    'Osimo',
    'San Benedetto del Tronto',
  ],
  'race-umag': ['Novigrad', 'Umag'],
  'race-valencia': ['Valencia', 'Gandia', 'Alcoy', 'Xativa', 'Sagunto', 'Valencia'],
  'race-valencia-gp': ['Valencia', 'Valencia'],
  'race-var': ['Draguignan', 'Draguignan'],
  'race-varese': ['Varese', 'Varese'],
  'race-veenendaal': ['Veenendaal', 'Veenendaal'],
  'race-vendee': ['La Roche-sur-Yon', 'La Roche-sur-Yon'],
  'race-vendemiano': ['Conegliano', 'San Vendemiano'],
  'race-veneto': ['Padova', 'Vicenza'],
  'race-veneto-classic': ['Venezia', 'Bassano del Grappa'],
  'race-venezuela': [
    'San Cristobal',
    'La Fria',
    'La Grita',
    'Bailadores',
    'Merida',
    'Timotes',
    'La Puerta',
    'Valera',
    'Bocono',
  ],
  'race-victoria': [
    'Melbourne',
    'Sorrento',
    'Arthurs Seat',
    'Melbourne',
    'Kinglake',
    'Healesville',
  ],
  'race-visegrad-cz': ['Brno', 'Blansko'],
  'race-vitre': ['Vitre', 'Vitre'],
  'race-vlaanderen': ['Brugge', 'Gent'],
  'race-vorarlberg': ['Bregenz', 'Bludenz'],
  'race-waasland': ['Sint-Niklaas', 'Lokeren'],
  'race-wallonia': ['Mons', 'Charleroi', 'Namur', 'Andenne', 'Huy', 'Liege'],
  'race-wallonie-circuit': ['Charleroi', 'Namur'],
  'race-walloon-wall': ['Namur', 'Huy'],
  'race-west-bohemia': ['Plzen', 'Karlovy Vary', 'Marianske Lazne', 'Cheb', 'Plzen'],
  'race-wevelgem': ['Ieper', 'Wevelgem'],
  'race-white-roads': ['Siena', 'Siena'],
  'race-woensdrecht': ['Bergen op Zoom', 'Woensdrecht'],
  'race-youngster': ['Nieuwpoort', 'Koksijde'],
  'race-zaglebie': ['Sosnowiec', 'Dabrowa Gornicza'],
  'race-zlm': ['Eindhoven', 'Weert', 'Sittard', 'Roermond', 'Valkenburg', 'Maastricht'],
  'race-zwolle': ['Zwolle', 'Zwolle'],
}

/** Recorrido completo de una carrera (localidades encadenadas), o null si no está definido. */
export function raceRoute(raceId: string): string[] | null {
  return RACE_ROUTES[raceId] ?? null
}

/** De dónde a dónde va una etapa concreta (1-based), o null si no hay recorrido/índice fuera de rango. */
export function stageEndpoints(
  raceId: string,
  stageIndex: number,
): { from: string; to: string } | null {
  const route = RACE_ROUTES[raceId]
  if (!route || stageIndex < 1 || stageIndex >= route.length) return null
  return { from: route[stageIndex - 1]!, to: route[stageIndex]! }
}
