/**
 * RASGOS REALES de las etapas (puertos puntuables y sprints intermedios reales) para las carreras
 * documentadas al detalle. De aquí sale una altimetría FIEL: cada puerto en su km real, con su longitud
 * y pendiente (de las que el motor deriva su categoría), y cada meta volante en su sitio. Las etapas sin
 * rasgos aquí caen al perfil por terreno (verosímil, no real).
 *
 * Mantenido desde los datos VERIFICADOS de cada carrera (perfiles oficiales / PCS-La Flamme Rouge). Un
 * puerto solo se anota si tiene km de cima + longitud + pendiente (si no, se descarta: no se inventa su
 * posición). Los km de cima salen del eje del perfil real; la categoría es la OFICIAL (ESP -> 'HC').
 * Clave: id de carrera -> array indexado por etapa (0-based); null = etapa con perfil por terreno.
 */
import type { StageFeatures } from './featureProfile.js'

export const STAGE_FEATURES: Record<string, (StageFeatures | null)[]> = {
  'race-france': [
    null,
    {
      climbs: [
        { name: 'Cote de Begues', summitKm: 93, lengthKm: 6.1, avgGradient: 6.5, category: 'cat3' },
        {
          name: "Cote de Santa Creu d'Olorda",
          summitKm: 132,
          lengthKm: 8.4,
          avgGradient: 4.5,
          category: 'cat3',
        },
        {
          name: 'Cote du Chateau de Montjuic',
          summitKm: 148,
          lengthKm: 1.3,
          avgGradient: 9.3,
          category: 'cat4',
        },
        {
          name: 'Cote du Chateau de Montjuic',
          summitKm: 158,
          lengthKm: 1.3,
          avgGradient: 9.3,
          category: 'cat4',
        },
        {
          name: 'Cote du Chateau de Montjuic',
          summitKm: 166,
          lengthKm: 1.3,
          avgGradient: 9.3,
          category: 'cat4',
        },
      ],
    },
    {
      climbs: [
        {
          name: 'Cote de Sant Feliu de Codines',
          summitKm: 42,
          lengthKm: 7.6,
          avgGradient: 4.6,
          category: 'cat3',
        },
        { name: 'Col de Toses', summitKm: 128, lengthKm: 9.3, avgGradient: 6.6, category: 'cat1' },
        {
          name: 'Col du Calvaire',
          summitKm: 165,
          lengthKm: 11.4,
          avgGradient: 4.1,
          category: 'cat3',
        },
        { name: 'Les Angles', summitKm: 196, lengthKm: 4.7, avgGradient: 4.6, category: 'cat3' },
      ],
    },
    {
      climbs: [
        { name: 'Col de Bedos', summitKm: 40, lengthKm: 3.3, avgGradient: 4.4, category: 'cat4' },
        { name: 'Col du Paradis', summitKm: 60, lengthKm: 5.8, avgGradient: 4.1, category: 'cat3' },
        {
          name: 'Col de Coudons',
          summitKm: 118,
          lengthKm: 10.7,
          avgGradient: 5.5,
          category: 'cat2',
        },
        {
          name: 'Col de Montsegur',
          summitKm: 146,
          lengthKm: 6.9,
          avgGradient: 6.6,
          category: 'cat2',
        },
      ],
    },
    null,
    {
      climbs: [
        {
          name: 'Cote de Loucrup',
          summitKm: 25,
          lengthKm: 1.9,
          avgGradient: 7.1,
          category: 'cat4',
        },
        { name: 'Cote de Mauvezin', summitKm: 42, lengthKm: 3, avgGradient: 6.8, category: 'cat3' },
        { name: "Col d'Aspin", summitKm: 118, lengthKm: 12, avgGradient: 6.5, category: 'cat1' },
        {
          name: 'Col du Tourmalet',
          summitKm: 148,
          lengthKm: 17.1,
          avgGradient: 7.3,
          category: 'HC',
        },
        {
          name: 'Gavarnie-Gedre',
          summitKm: 186,
          lengthKm: 18.7,
          avgGradient: 3.7,
          category: 'cat2',
        },
      ],
    },
    null,
    null,
    {
      climbs: [
        { name: 'Suc au May', summitKm: 105, lengthKm: 3.9, avgGradient: 7.7, category: 'cat2' },
        { name: 'Mont Bessou', summitKm: 161, lengthKm: 1, avgGradient: 8.5, category: 'cat4' },
      ],
    },
    {
      climbs: [
        {
          name: 'Cote de Pailherols',
          summitKm: 68,
          lengthKm: 3.3,
          avgGradient: 6.5,
          category: 'cat3',
        },
        {
          name: 'Col de la Griffoul',
          summitKm: 97,
          lengthKm: 5.9,
          avgGradient: 6.7,
          category: 'cat2',
        },
        {
          name: 'Col de Prat de Bouc',
          summitKm: 104,
          lengthKm: 3.2,
          avgGradient: 5.8,
          category: 'cat3',
        },
        { name: 'Cote de Murat', summitKm: 119, lengthKm: 6.6, avgGradient: 4.4, category: 'cat3' },
        { name: 'Col de Pertus', summitKm: 152, lengthKm: 4.4, avgGradient: 8.5, category: 'cat1' },
        {
          name: 'Montee du Lioran',
          summitKm: 164,
          lengthKm: 0.9,
          avgGradient: 7.4,
          category: 'cat3',
        },
      ],
    },
    null,
    null,
    {
      climbs: [
        { name: 'Col des Croix', summitKm: 157, lengthKm: 5.1, avgGradient: 4.6, category: 'cat3' },
        {
          name: "Ballon d'Alsace",
          summitKm: 176,
          lengthKm: 8.9,
          avgGradient: 6.8,
          category: 'cat1',
        },
      ],
    },
    {
      climbs: [
        { name: 'Grand Ballon', summitKm: 52, lengthKm: 21.5, avgGradient: 4.8, category: 'cat1' },
        { name: 'Col du Page', summitKm: 100, lengthKm: 9.8, avgGradient: 4.7, category: 'cat2' },
        {
          name: "Ballon d'Alsace",
          summitKm: 125,
          lengthKm: 8.9,
          avgGradient: 6.9,
          category: 'cat1',
        },
        { name: 'Col du Haag', summitKm: 143, lengthKm: 11.2, avgGradient: 7.3, category: 'cat1' },
      ],
    },
    {
      climbs: [
        {
          name: 'Col de la Croisette',
          summitKm: 134,
          lengthKm: 4.6,
          avgGradient: 11.2,
          category: 'cat1',
        },
        {
          name: 'Plateau de Solaison',
          summitKm: 184,
          lengthKm: 11.3,
          avgGradient: 9.1,
          category: 'HC',
        },
      ],
    },
    null,
    {
      climbs: [
        { name: 'Cote de Bassa', summitKm: 19, lengthKm: 1.5, avgGradient: 5.6, category: 'cat4' },
        { name: 'Col des Pres', summitKm: 50, lengthKm: 3.5, avgGradient: 6.8, category: 'cat3' },
        { name: 'Col de Couz', summitKm: 60, lengthKm: 8.6, avgGradient: 2.8, category: 'cat4' },
      ],
    },
    {
      climbs: [
        { name: "Cote d'Engins", summitKm: 37, lengthKm: 11.4, avgGradient: 5.4, category: 'cat1' },
        {
          name: 'Cote de Monteynard',
          summitKm: 92,
          lengthKm: 9.7,
          avgGradient: 5,
          category: 'cat2',
        },
        {
          name: 'Cote des Terrasses',
          summitKm: 113,
          lengthKm: 3.4,
          avgGradient: 6.6,
          category: 'cat3',
        },
        {
          name: 'Cote de Saint-Leger-les-Melezes',
          summitKm: 166,
          lengthKm: 2.5,
          avgGradient: 6.9,
          category: 'cat3',
        },
        {
          name: 'Orcieres-Merlette',
          summitKm: 185,
          lengthKm: 7.1,
          avgGradient: 6.7,
          category: 'cat1',
        },
      ],
    },
    {
      climbs: [
        { name: 'Col Bayard', summitKm: 9, lengthKm: 4.7, avgGradient: 7.2, category: 'cat2' },
        { name: 'Col du Noyer', summitKm: 25, lengthKm: 7.2, avgGradient: 8.5, category: 'cat1' },
        { name: "Col d'Ornon", summitKm: 99, lengthKm: 5.4, avgGradient: 6.4, category: 'cat2' },
        { name: "Alpe d'Huez", summitKm: 128, lengthKm: 13.8, avgGradient: 8.1, category: 'HC' },
      ],
    },
    {
      climbs: [
        {
          name: 'Col de la Croix de Fer',
          summitKm: 30,
          lengthKm: 24,
          avgGradient: 5.2,
          category: 'HC',
        },
        {
          name: 'Col du Telegraphe',
          summitKm: 90,
          lengthKm: 11.9,
          avgGradient: 7.1,
          category: 'cat1',
        },
        {
          name: 'Col du Galibier',
          summitKm: 110,
          lengthKm: 17.7,
          avgGradient: 6.9,
          category: 'HC',
        },
        { name: 'Col de Sarenne', summitKm: 150, lengthKm: 12.8, avgGradient: 7.3, category: 'HC' },
        { name: "Alpe d'Huez", summitKm: 171, lengthKm: 13.8, avgGradient: 8.1, category: 'HC' },
      ],
      sprints: [{ name: 'Saint-Julien-Mont-Denis', km: 78 }],
    },
  ],
  'race-galicia': [
    {
      climbs: [
        { name: 'Alto de Feitos', summitKm: 51, lengthKm: 6, avgGradient: 4.2 },
        { name: 'Alto de Sao Felix', summitKm: 144, lengthKm: 1.3, avgGradient: 6.9 },
      ],
      sprints: [{ name: 'Barroselas', km: 67 }],
    },
    {
      climbs: [
        {
          name: 'Alto de San Antonino',
          summitKm: 18,
          lengthKm: 2.3,
          avgGradient: 6.5,
          category: 'cat3',
        },
        {
          name: 'Santa Lucia de Morana',
          summitKm: 24.5,
          lengthKm: 2,
          avgGradient: 5,
          category: 'cat4',
        },
        {
          name: 'Alto de San Vicenzo',
          summitKm: 86.5,
          lengthKm: 2.6,
          avgGradient: 6.9,
          category: 'cat3',
        },
        { name: 'A Estrada', summitKm: 97, lengthKm: 1.9, avgGradient: 5.6, category: 'cat4' },
        {
          name: 'Alto de San Vicenzo',
          summitKm: 122,
          lengthKm: 2.5,
          avgGradient: 7.2,
          category: 'cat3',
        },
      ],
      sprints: [
        { name: 'Barro', km: 16 },
        { name: 'A Estrada', km: 74 },
      ],
    },
    null,
    {
      climbs: [
        {
          name: 'Alto de Catro Ventos',
          summitKm: 98,
          lengthKm: 8.4,
          avgGradient: 5.7,
          category: 'cat2',
        },
        {
          name: 'A Pintinidoira',
          summitKm: 122,
          lengthKm: 13.3,
          avgGradient: 5.7,
          category: 'cat1',
        },
        { name: 'O Cebreiro', summitKm: 135, lengthKm: 2.8, avgGradient: 6.5, category: 'cat3' },
      ],
    },
    {
      climbs: [
        { name: 'Repecho inicial', summitKm: 14, lengthKm: 4.2, avgGradient: 6.4 },
        { name: 'Alto de Lampai', summitKm: 105, lengthKm: 5.2, avgGradient: 5.4 },
        { name: 'Alto de Lampai', summitKm: 150, lengthKm: 5.2, avgGradient: 5.4 },
      ],
    },
  ],
  'race-italy': [
    null,
    {
      climbs: [
        { name: 'Byala Pass', summitKm: 138, lengthKm: 7.7, avgGradient: 4.6, category: 'cat3' },
        { name: 'Vratnik Pass', summitKm: 151, lengthKm: 9.2, avgGradient: 4, category: 'cat3' },
        {
          name: 'Lyaskovets Monastery Pass',
          summitKm: 210,
          lengthKm: 3.9,
          avgGradient: 6.8,
          category: 'cat3',
        },
      ],
    },
    null,
    null,
    {
      climbs: [
        { name: 'Prestieri', summitKm: 27, lengthKm: 13.6, avgGradient: 4.8, category: 'cat3' },
        {
          name: 'Montagna Grande di Viggiano',
          summitKm: 154,
          lengthKm: 6.6,
          avgGradient: 9.1,
          category: 'cat2',
        },
      ],
    },
    null,
    {
      climbs: [
        { name: 'Roccaraso', summitKm: 166, lengthKm: 6.9, avgGradient: 6.5, category: 'cat2' },
        { name: 'Blockhaus', summitKm: 244, lengthKm: 13.6, avgGradient: 8.4, category: 'cat1' },
      ],
    },
    null,
    {
      climbs: [
        { name: 'Querciola', summitKm: 160, lengthKm: 11.3, avgGradient: 4.3, category: 'cat3' },
        {
          name: 'Corno alle Scale',
          summitKm: 184,
          lengthKm: 10.8,
          avgGradient: 6.1,
          category: 'cat1',
        },
      ],
    },
    null,
    null,
    null,
    null,
    {
      climbs: [
        {
          name: 'Col du Saint-Barthelemy',
          summitKm: 18,
          lengthKm: 15.8,
          avgGradient: 6.1,
          category: 'cat1',
        },
        { name: 'Doues', summitKm: 62, lengthKm: 5.8, avgGradient: 6.2, category: 'cat3' },
        { name: 'Lin Noir', summitKm: 82, lengthKm: 7.4, avgGradient: 7.9, category: 'cat1' },
        { name: 'Verrogne', summitKm: 92, lengthKm: 5.6, avgGradient: 6.9, category: 'cat2' },
        { name: 'Pila-Gressan', summitKm: 133, lengthKm: 16.5, avgGradient: 7.1, category: 'cat1' },
      ],
    },
    null,
    {
      climbs: [
        { name: 'Torre', summitKm: 32, lengthKm: 4.7, avgGradient: 5.6, category: 'cat3' },
        { name: 'Leontica', summitKm: 44, lengthKm: 3, avgGradient: 8.5, category: 'cat2' },
        { name: 'Torre', summitKm: 54, lengthKm: 4.7, avgGradient: 5.6, category: 'cat3' },
        { name: 'Leontica', summitKm: 66, lengthKm: 3, avgGradient: 8.5, category: 'cat2' },
        { name: 'Cari', summitKm: 113, lengthKm: 11.7, avgGradient: 7.9, category: 'cat1' },
      ],
    },
    null,
    {
      climbs: [
        {
          name: "Muro di Ca' del Poggio",
          summitKm: 162,
          lengthKm: 1.1,
          avgGradient: 12.3,
          category: 'cat4',
        },
      ],
    },
    {
      climbs: [
        { name: 'Passo Duran', summitKm: 59, lengthKm: 12.1, avgGradient: 8.2, category: 'cat1' },
        { name: 'Coi', summitKm: 73, lengthKm: 5.8, avgGradient: 9.7, category: 'cat2' },
        {
          name: 'Forcella Staulanza',
          summitKm: 82,
          lengthKm: 6.3,
          avgGradient: 6.7,
          category: 'cat2',
        },
        { name: 'Passo Giau', summitKm: 102, lengthKm: 9.9, avgGradient: 9.3, category: 'HC' },
        {
          name: 'Passo Falzarego',
          summitKm: 122,
          lengthKm: 10.1,
          avgGradient: 5.6,
          category: 'cat2',
        },
        {
          name: 'Piani di Pezze',
          summitKm: 151,
          lengthKm: 4.9,
          avgGradient: 9.7,
          category: 'cat1',
        },
      ],
    },
    {
      climbs: [
        { name: 'Clauzetto', summitKm: 86, lengthKm: 6.9, avgGradient: 5.7, category: 'cat3' },
        { name: 'Piancavallo', summitKm: 147, lengthKm: 11.1, avgGradient: 7, category: 'cat1' },
        { name: 'Piancavallo', summitKm: 200, lengthKm: 14.5, avgGradient: 7.8, category: 'cat1' },
      ],
    },
  ],
  'race-spain': [
    {
      elevation: [
        { km: 0, elevM: 50 },
        { km: 4, elevM: 22 },
        { km: 5, elevM: 0 },
        { km: 7.3, elevM: 7 },
        { km: 8.9, elevM: 17 },
        { km: 9.6, elevM: 10 },
      ],
    },
    {
      climbs: [
        {
          name: 'Alto Chateauneuf-Grasse',
          summitKm: 44.4,
          lengthKm: 11.5,
          avgGradient: 3,
          category: 'cat3',
        },
        {
          name: 'Col de Saint Andrieu',
          summitKm: 106,
          lengthKm: 4.3,
          avgGradient: 5.2,
          category: 'cat3',
        },
      ],
      elevation: [
        { km: 0, elevM: 230 },
        { km: 5, elevM: 110 },
        { km: 29.3, elevM: 20 },
        { km: 37.6, elevM: 190 },
        { km: 44.7, elevM: 410 },
        { km: 50.6, elevM: 340 },
        { km: 56.8, elevM: 190 },
        { km: 75.5, elevM: 210 },
        { km: 83.4, elevM: 260 },
        { km: 105, elevM: 500 },
        { km: 116, elevM: 570 },
        { km: 126, elevM: 611 },
        { km: 134, elevM: 510 },
        { km: 149, elevM: 480 },
        { km: 166, elevM: 390 },
        { km: 179, elevM: 330 },
        { km: 192, elevM: 550 },
        { km: 215, elevM: 410 },
      ],
    },
    {
      climbs: [
        {
          name: 'Col de Mont-Louis',
          summitKm: 148.1,
          lengthKm: 19,
          avgGradient: 5,
          category: 'cat1',
        },
        {
          name: 'Font-Romeu',
          summitKm: 166.7,
          lengthKm: 9.8,
          avgGradient: 4.9,
          category: 'cat2',
        },
      ],
      elevation: [
        { km: 0, elevM: 32 },
        { km: 8, elevM: 6 },
        { km: 30, elevM: 16 },
        { km: 46, elevM: 5 },
        { km: 65, elevM: 27 },
        { km: 94.5, elevM: 154 },
        { km: 113.5, elevM: 333 },
        { km: 139.7, elevM: 1076 },
        { km: 146.1, elevM: 1566 },
        { km: 155, elevM: 1449 },
        { km: 166.7, elevM: 1932 },
      ],
    },
    {
      climbs: [
        {
          name: "Port d'Envalira",
          summitKm: 26,
          lengthKm: 24.4,
          avgGradient: 5,
          category: 'cat1',
        },
        {
          name: 'Collada de Beixalis',
          summitKm: 60,
          lengthKm: 6.5,
          avgGradient: 8.6,
          category: 'cat1',
        },
        {
          name: "Coll d'Ordino",
          summitKm: 80,
          lengthKm: 9.9,
          avgGradient: 7,
          category: 'cat1',
        },
        {
          name: 'Alto de La Comella',
          summitKm: 101,
          lengthKm: 3.8,
          avgGradient: 5.4,
          category: 'cat3',
        },
      ],
      elevation: [
        { km: 0, elevM: 1138 },
        { km: 3, elevM: 1269 },
        { km: 14, elevM: 1683 },
        { km: 26, elevM: 2407 },
        { km: 31, elevM: 2090 },
        { km: 43, elevM: 1689 },
        { km: 56, elevM: 1244 },
        { km: 60, elevM: 1801 },
        { km: 70, elevM: 1289 },
        { km: 80, elevM: 1982 },
        { km: 93, elevM: 1321 },
        { km: 97, elevM: 1132 },
        { km: 101, elevM: 1344 },
        { km: 105, elevM: 1014 },
      ],
    },
    {
      climbs: [
        {
          name: 'Alto de Pauls',
          summitKm: 147.5,
          lengthKm: 3.9,
          avgGradient: 6.6,
          category: 'cat3',
        },
      ],
      elevation: [
        { km: 0, elevM: 363 },
        { km: 15.5, elevM: 42 },
        { km: 50.5, elevM: 132 },
        { km: 58.5, elevM: 11 },
        { km: 72, elevM: 2 },
        { km: 85.5, elevM: 12 },
        { km: 101.5, elevM: 2 },
        { km: 119, elevM: 180 },
        { km: 126, elevM: 18 },
        { km: 130, elevM: 185 },
        { km: 147.5, elevM: 383 },
        { km: 171.1, elevM: 17 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto de La Serratella',
          summitKm: 40,
          lengthKm: 11.5,
          avgGradient: 4.8,
          category: 'cat2',
        },
        {
          name: 'Coll de la Bandereta',
          summitKm: 63,
          lengthKm: 4.6,
          avgGradient: 6.6,
          category: 'cat3',
        },
        {
          name: 'Alto del Desierto de las Palmas',
          summitKm: 124,
          lengthKm: 7.2,
          avgGradient: 5.2,
          category: 'cat2',
        },
        {
          name: 'Alto del Bartolo',
          summitKm: 151,
          lengthKm: 9.1,
          avgGradient: 7.2,
          category: 'cat1',
        },
      ],
      elevation: [
        { km: 0, elevM: 63 },
        { km: 4, elevM: 156 },
        { km: 22, elevM: 190 },
        { km: 40, elevM: 800 },
        { km: 51, elevM: 535 },
        { km: 63, elevM: 780 },
        { km: 78, elevM: 311 },
        { km: 91.5, elevM: 282 },
        { km: 117.9, elevM: 24 },
        { km: 125.5, elevM: 418 },
        { km: 144, elevM: 24 },
        { km: 148, elevM: 346 },
        { km: 152, elevM: 639 },
        { km: 176.8, elevM: 27 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto El Remolcador',
          summitKm: 52.5,
          lengthKm: 12,
          avgGradient: 4.4,
          category: 'cat2',
        },
        {
          name: 'Alto de Zucaina',
          summitKm: 66.5,
          lengthKm: 5.3,
          avgGradient: 4.8,
          category: 'cat3',
        },
        {
          name: 'Alto Fuente de Rubielos',
          summitKm: 103.5,
          lengthKm: 6.1,
          avgGradient: 6.1,
          category: 'cat3',
        },
        {
          name: 'Puerto de San Rafael',
          summitKm: 133.5,
          lengthKm: 9.5,
          avgGradient: 4.4,
          category: 'cat2',
        },
        {
          name: 'Aramon Valdelinares',
          summitKm: 149.9,
          lengthKm: 8.3,
          avgGradient: 6.5,
          category: 'cat1',
        },
      ],
      elevation: [
        { km: 0, elevM: 251 },
        { km: 20, elevM: 381 },
        { km: 41.9, elevM: 566 },
        { km: 51.9, elevM: 983 },
        { km: 66.5, elevM: 809 },
        { km: 84, elevM: 630 },
        { km: 105.3, elevM: 1003 },
        { km: 110.3, elevM: 942 },
        { km: 133.3, elevM: 1363 },
        { km: 136.3, elevM: 1561 },
        { km: 149.9, elevM: 1961 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto de Barx',
          summitKm: 147,
          lengthKm: 8.6,
          avgGradient: 3.8,
          category: 'cat2',
        },
      ],
      elevation: [
        { km: 0, elevM: 18 },
        { km: 15.5, elevM: 33 },
        { km: 28, elevM: 171 },
        { km: 44, elevM: 102 },
        { km: 65.5, elevM: 206 },
        { km: 87, elevM: 160 },
        { km: 107, elevM: 54 },
        { km: 116.5, elevM: 19 },
        { km: 142.5, elevM: 310 },
        { km: 147, elevM: 387 },
        { km: 167.4, elevM: 15 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto de Tarbena',
          summitKm: 36.5,
          lengthKm: 6.7,
          avgGradient: 5.4,
          category: 'cat2',
        },
        {
          name: 'Puerto de El Miserat',
          summitKm: 74.5,
          lengthKm: 5,
          avgGradient: 10.1,
          category: 'cat1',
        },
        {
          name: 'Port de Tollos',
          summitKm: 91.3,
          lengthKm: 4,
          avgGradient: 5.7,
          category: 'cat3',
        },
        {
          name: 'Port de Tudons',
          summitKm: 122.5,
          lengthKm: 11.7,
          avgGradient: 4,
          category: 'cat2',
        },
        {
          name: 'Port de Benifallim',
          summitKm: 141,
          lengthKm: 4.8,
          avgGradient: 5.9,
          category: 'cat3',
        },
        {
          name: 'Alto de Aitana',
          summitKm: 187.5,
          lengthKm: 21,
          avgGradient: 5.8,
          category: 'cat1',
        },
      ],
      elevation: [
        { km: 0, elevM: 98 },
        { km: 8, elevM: 248 },
        { km: 19, elevM: 241 },
        { km: 24.5, elevM: 290 },
        { km: 36.5, elevM: 590 },
        { km: 44, elevM: 625 },
        { km: 56.5, elevM: 152 },
        { km: 74.5, elevM: 627 },
        { km: 91.5, elevM: 821 },
        { km: 102, elevM: 618 },
        { km: 122.5, elevM: 1020 },
        { km: 130.3, elevM: 698 },
        { km: 141, elevM: 1013 },
        { km: 149, elevM: 888 },
        { km: 160, elevM: 442 },
        { km: 167.7, elevM: 281 },
        { km: 181, elevM: 1030 },
        { km: 187.5, elevM: 1544 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto del Peralejo',
          summitKm: 47,
          lengthKm: 4.9,
          avgGradient: 4.5,
          category: 'cat3',
        },
        {
          name: 'Puerto de Ayna',
          summitKm: 88,
          lengthKm: 8.1,
          avgGradient: 4,
          category: 'cat3',
        },
        {
          name: 'Puerto de Socovos',
          summitKm: 154.5,
          lengthKm: 9.8,
          avgGradient: 3.5,
          category: 'cat3',
        },
      ],
      elevation: [
        { km: 0, elevM: 837 },
        { km: 8, elevM: 824 },
        { km: 26, elevM: 1295 },
        { km: 39, elevM: 969 },
        { km: 47, elevM: 1129 },
        { km: 74, elevM: 685 },
        { km: 88, elevM: 948 },
        { km: 124, elevM: 552 },
        { km: 147, elevM: 604 },
        { km: 149, elevM: 528 },
        { km: 151, elevM: 706 },
        { km: 154.5, elevM: 774 },
        { km: 163, elevM: 558 },
        { km: 184.5, elevM: 645 },
      ],
    },
    {
      climbs: [
        {
          name: 'Alto del Morrion de Totana',
          summitKm: 120,
          lengthKm: 8.8,
          avgGradient: 4.3,
          category: 'cat3',
        },
      ],
      elevation: [
        { km: 0, elevM: 25 },
        { km: 6.5, elevM: 205 },
        { km: 10, elevM: 40 },
        { km: 13, elevM: 138 },
        { km: 20.5, elevM: 29 },
        { km: 40, elevM: 5 },
        { km: 53, elevM: 39 },
        { km: 77.3, elevM: 135 },
        { km: 111.9, elevM: 239 },
        { km: 120, elevM: 626 },
        { km: 156.1, elevM: 339 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto Los Barrancos',
          summitKm: 19,
          lengthKm: 4.9,
          avgGradient: 3.9,
          category: 'cat3',
        },
        {
          name: 'Puerto de la Virgen',
          summitKm: 57.5,
          lengthKm: 3.7,
          avgGradient: 5.2,
          category: 'cat3',
        },
        {
          name: 'Collado Garcia',
          summitKm: 88.5,
          lengthKm: 18.9,
          avgGradient: 2.4,
          category: 'cat2',
        },
        {
          name: 'Alto de Velefique',
          summitKm: 135,
          lengthKm: 11,
          avgGradient: 7,
          category: 'cat1',
        },
        {
          name: 'Calar Alto',
          summitKm: 166.5,
          lengthKm: 17.1,
          avgGradient: 5.6,
          category: 'cat1',
        },
      ],
      elevation: [
        { km: 0, elevM: 117 },
        { km: 18, elevM: 472 },
        { km: 35.5, elevM: 407 },
        { km: 57.5, elevM: 667 },
        { km: 70, elevM: 948 },
        { km: 76.5, elevM: 1163 },
        { km: 88.5, elevM: 1240 },
        { km: 107, elevM: 464 },
        { km: 122, elevM: 845 },
        { km: 135, elevM: 1786 },
        { km: 148.5, elevM: 1188 },
        { km: 156, elevM: 1799 },
        { km: 166.5, elevM: 2151 },
      ],
    },
    {
      climbs: [
        {
          name: 'Venta de la Cebada',
          summitKm: 25,
          lengthKm: 14.1,
          avgGradient: 5.1,
          category: 'cat1',
        },
        {
          name: 'Puerto Las Albunuelas',
          summitKm: 43,
          lengthKm: 2.3,
          avgGradient: 9.2,
          category: 'cat2',
        },
        {
          name: 'Alto del Legionario',
          summitKm: 100,
          lengthKm: 9.3,
          avgGradient: 3.4,
          category: 'cat2',
        },
        {
          name: 'Puerto de Granada',
          summitKm: 154,
          lengthKm: 6.7,
          avgGradient: 6.1,
          category: 'cat2',
        },
      ],
      elevation: [
        { km: 0, elevM: 85 },
        { km: 20.5, elevM: 327 },
        { km: 28, elevM: 822 },
        { km: 35.5, elevM: 711 },
        { km: 43.5, elevM: 739 },
        { km: 49, elevM: 867 },
        { km: 68.1, elevM: 743 },
        { km: 92.5, elevM: 1351 },
        { km: 105.5, elevM: 846 },
        { km: 110.5, elevM: 1033 },
        { km: 142, elevM: 590 },
        { km: 155, elevM: 819 },
        { km: 160, elevM: 1030 },
        { km: 181, elevM: 481 },
        { km: 193.2, elevM: 498 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puertoviejo',
          summitKm: 90,
          lengthKm: 11.3,
          avgGradient: 5.3,
          category: 'cat2',
        },
        {
          name: 'Puerto de Locubin',
          summitKm: 129,
          lengthKm: 9,
          avgGradient: 5,
          category: 'cat2',
        },
        {
          name: 'Sierra de La Pandera',
          summitKm: 152.7,
          lengthKm: 8.5,
          avgGradient: 7.9,
          category: 'cat1',
        },
      ],
      elevation: [
        { km: 0, elevM: 391 },
        { km: 14, elevM: 757 },
        { km: 33, elevM: 841 },
        { km: 46.5, elevM: 774 },
        { km: 50, elevM: 917 },
        { km: 60, elevM: 580 },
        { km: 76, elevM: 756 },
        { km: 80, elevM: 621 },
        { km: 90.5, elevM: 1186 },
        { km: 100, elevM: 719 },
        { km: 109, elevM: 757 },
        { km: 113.5, elevM: 719 },
        { km: 120, elevM: 636 },
        { km: 130, elevM: 1091 },
        { km: 137.5, elevM: 976 },
        { km: 141, elevM: 1144 },
        { km: 152.7, elevM: 1821 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto del Mojon Blanco',
          summitKm: 37,
          lengthKm: 7.5,
          avgGradient: 4.4,
          category: 'cat3',
        },
        {
          name: 'Alto de Villaviciosa de Cordoba',
          summitKm: 126,
          lengthKm: 8.4,
          avgGradient: 3.5,
          category: 'cat3',
        },
        {
          name: 'Puerto Artafi',
          summitKm: 156,
          lengthKm: 5.9,
          avgGradient: 5.5,
          category: 'cat3',
        },
      ],
      elevation: [
        { km: 0, elevM: 63 },
        { km: 23.5, elevM: 91 },
        { km: 39, elevM: 500 },
        { km: 63, elevM: 648 },
        { km: 81, elevM: 527 },
        { km: 108, elevM: 631 },
        { km: 126.5, elevM: 734 },
        { km: 149, elevM: 432 },
        { km: 158, elevM: 518 },
        { km: 181.2, elevM: 98 },
      ],
    },
    {
      elevation: [
        { km: 0, elevM: 652 },
        { km: 8, elevM: 470 },
        { km: 23, elevM: 802 },
        { km: 26, elevM: 831 },
        { km: 34, elevM: 696 },
        { km: 39.5, elevM: 651 },
        { km: 56, elevM: 552 },
        { km: 68, elevM: 433 },
        { km: 83, elevM: 356 },
        { km: 96, elevM: 327 },
        { km: 120, elevM: 80 },
        { km: 163.7, elevM: 32 },
        { km: 179.5, elevM: 35 },
        { km: 186, elevM: 26 },
      ],
    },
    {
      elevation: [
        { km: 0, elevM: 39 },
        { km: 9.5, elevM: 12 },
        { km: 23, elevM: 50 },
        { km: 44, elevM: 136 },
        { km: 62, elevM: 201 },
        { km: 90, elevM: 45 },
        { km: 111.5, elevM: 67 },
        { km: 137.5, elevM: 221 },
        { km: 156.5, elevM: 32 },
        { km: 171.5, elevM: 13 },
        { km: 189.2, elevM: 11 },
      ],
    },
    {
      elevation: [
        { km: 0, elevM: 10 },
        { km: 11, elevM: 45 },
        { km: 20, elevM: 6 },
        { km: 26, elevM: 28 },
        { km: 32.5, elevM: 53 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto de las Abejas',
          summitKm: 88,
          lengthKm: 14.4,
          avgGradient: 4.3,
          category: 'cat2',
        },
        {
          name: 'Puerto de los Empedrados',
          summitKm: 101,
          lengthKm: 7.1,
          avgGradient: 5.8,
          category: 'cat3',
        },
        {
          name: 'Puerto Cerro Mojon',
          summitKm: 138,
          lengthKm: 14.8,
          avgGradient: 2.9,
          category: 'cat3',
        },
        {
          name: 'Penas Blancas',
          summitKm: 205.1,
          lengthKm: 18.7,
          avgGradient: 6.5,
          category: 'cat1',
        },
      ],
      elevation: [
        { km: 0, elevM: 2 },
        { km: 12, elevM: 7 },
        { km: 27.5, elevM: 14 },
        { km: 46.5, elevM: 81 },
        { km: 60, elevM: 181 },
        { km: 79, elevM: 373 },
        { km: 90, elevM: 823 },
        { km: 96, elevM: 620 },
        { km: 103.5, elevM: 975 },
        { km: 110, elevM: 1058 },
        { km: 121.5, elevM: 722 },
        { km: 139, elevM: 1123 },
        { km: 170, elevM: 15 },
        { km: 187, elevM: 48 },
        { km: 190, elevM: 250 },
        { km: 200, elevM: 974 },
        { km: 205.1, elevM: 1270 },
      ],
    },
    {
      climbs: [
        {
          name: 'Puerto de Blancares',
          summitKm: 52.5,
          lengthKm: 9.3,
          avgGradient: 3.4,
          category: 'cat3',
        },
        {
          name: 'Alto de Hazallanas',
          summitKm: 90.5,
          lengthKm: 7.1,
          avgGradient: 9.5,
          category: 'cat1',
        },
        {
          name: 'Puerto de El Purche',
          summitKm: 128.3,
          lengthKm: 9.1,
          avgGradient: 7.4,
          category: 'cat1',
        },
        {
          name: 'Alto de Hazallanas',
          summitKm: 155.6,
          lengthKm: 7.1,
          avgGradient: 9.5,
          category: 'cat1',
        },
        {
          name: 'Collado del Alguacil',
          summitKm: 187,
          lengthKm: 8.3,
          avgGradient: 9.8,
          category: 'HC',
        },
      ],
      elevation: [
        { km: 0, elevM: 1186 },
        { km: 10, elevM: 1241 },
        { km: 24, elevM: 917 },
        { km: 52.8, elevM: 1292 },
        { km: 74, elevM: 773 },
        { km: 81.6, elevM: 1066 },
        { km: 90.5, elevM: 1668 },
        { km: 115, elevM: 719 },
        { km: 128.3, elevM: 1483 },
        { km: 139.2, elevM: 773 },
        { km: 146.8, elevM: 1066 },
        { km: 155.6, elevM: 1668 },
        { km: 172, elevM: 1150 },
        { km: 186.8, elevM: 1882 },
      ],
    },
    {
      elevation: [
        { km: 0, elevM: 662 },
        { km: 9, elevM: 662 },
        { km: 17, elevM: 749 },
        { km: 24, elevM: 799 },
        { km: 30.5, elevM: 789 },
        { km: 40, elevM: 649 },
        { km: 46.5, elevM: 586 },
        { km: 59, elevM: 650 },
        { km: 64.5, elevM: 780 },
        { km: 68.5, elevM: 655 },
        { km: 72.5, elevM: 780 },
        { km: 77, elevM: 655 },
        { km: 81.5, elevM: 780 },
        { km: 88, elevM: 815 },
        { km: 90.5, elevM: 780 },
        { km: 94, elevM: 655 },
        { km: 99.4, elevM: 780 },
      ],
    },
  ],
}
